"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from continuous.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .advance_simulationop import (
        AdvanceSimulationRequest,
        AdvanceSimulationRequestTypedDict,
    )
    from .advance_worldop import AdvanceWorldRequest, AdvanceWorldRequestTypedDict
    from .advancetimerequest import AdvanceTimeRequest, AdvanceTimeRequestTypedDict
    from .build_simulatorop import (
        BuildSimulatorResponse,
        BuildSimulatorResponseTypedDict,
        SimulatorsBuildSimulatorRequest,
        SimulatorsBuildSimulatorRequestTypedDict,
        Spec,
        SpecTypedDict,
    )
    from .buildsimulatorrequest import (
        BuildSimulatorRequest,
        BuildSimulatorRequestModel,
        BuildSimulatorRequestSpecKind,
        BuildSimulatorRequestTypedDict,
    )
    from .buildworldrequest import (
        BuildWorldRequest,
        BuildWorldRequestModel,
        BuildWorldRequestTypedDict,
    )
    from .cancel_simulatorop import (
        CancelSimulatorRequest,
        CancelSimulatorRequestTypedDict,
    )
    from .cancel_worldop import CancelWorldRequest, CancelWorldRequestTypedDict
    from .clockadvance import ClockAdvance, ClockAdvanceStatus, ClockAdvanceTypedDict
    from .clockadvancemember import (
        ClockAdvanceMember,
        ClockAdvanceMemberStatus,
        ClockAdvanceMemberTypedDict,
    )
    from .clockevent import ClockEvent, ClockEventTypedDict
    from .create_simulationop import (
        CreateSimulationResponse,
        CreateSimulationResponseTypedDict,
    )
    from .createdsimulation import (
        CreatedSimulation,
        CreatedSimulationStatus,
        CreatedSimulationTypedDict,
    )
    from .createsimulationrequest import (
        CreateSimulationRequest,
        CreateSimulationRequestTypedDict,
    )
    from .currentsimulationtoken import (
        CurrentSimulationToken,
        CurrentSimulationTokenTypedDict,
    )
    from .delete_simulationop import (
        DeleteSimulationRequest,
        DeleteSimulationRequestTypedDict,
    )
    from .delete_simulatorop import (
        DeleteSimulatorRequest,
        DeleteSimulatorRequestTypedDict,
    )
    from .delete_worldop import DeleteWorldRequest, DeleteWorldRequestTypedDict
    from .fork_simulationop import (
        ForkSimulationRequestRequest,
        ForkSimulationRequestRequestTypedDict,
        ForkSimulationResponse,
        ForkSimulationResponseTypedDict,
    )
    from .forksimulationrequest import (
        ForkSimulationRequest,
        ForkSimulationRequestTypedDict,
    )
    from .get_simulation_advanceop import (
        GetSimulationAdvanceRequest,
        GetSimulationAdvanceRequestTypedDict,
    )
    from .get_simulation_tokenop import (
        GetSimulationTokenRequest,
        GetSimulationTokenRequestTypedDict,
        GetSimulationTokenResponse,
        GetSimulationTokenResponseTypedDict,
    )
    from .get_simulationop import GetSimulationRequest, GetSimulationRequestTypedDict
    from .get_simulatorop import GetSimulatorRequest, GetSimulatorRequestTypedDict
    from .get_world_advanceop import (
        GetWorldAdvanceRequest,
        GetWorldAdvanceRequestTypedDict,
    )
    from .get_worldop import GetWorldRequest, GetWorldRequestTypedDict
    from .list_simulation_advance_eventsop import (
        ListSimulationAdvanceEventsRequest,
        ListSimulationAdvanceEventsRequestTypedDict,
    )
    from .list_simulation_stepsop import (
        ListSimulationStepsRequest,
        ListSimulationStepsRequestTypedDict,
    )
    from .list_simulationsop import (
        ListSimulationsRequest,
        ListSimulationsRequestTypedDict,
        ListSimulationsStatus,
    )
    from .list_simulatorsop import (
        ListSimulatorsRequest,
        ListSimulatorsRequestTypedDict,
        ListSimulatorsStatus,
    )
    from .list_worldsop import (
        ListWorldsRequest,
        ListWorldsRequestTypedDict,
        ListWorldsStatus,
    )
    from .listclockadvanceeventsresponse import (
        ListClockAdvanceEventsResponse,
        ListClockAdvanceEventsResponseTypedDict,
    )
    from .listsimulationsresponse import (
        ListSimulationsResponse,
        ListSimulationsResponseTypedDict,
    )
    from .listsimulationstepsresponse import (
        ListSimulationStepsResponse,
        ListSimulationStepsResponseTypedDict,
    )
    from .listsimulatorsresponse import (
        ListSimulatorsResponse,
        ListSimulatorsResponseTypedDict,
    )
    from .listworldsresponse import ListWorldsResponse, ListWorldsResponseTypedDict
    from .regenerate_simulation_tokenop import (
        RegenerateSimulationTokenRequest,
        RegenerateSimulationTokenRequestTypedDict,
        RegenerateSimulationTokenResponse,
        RegenerateSimulationTokenResponseTypedDict,
    )
    from .resourceerror import ResourceError, ResourceErrorTypedDict
    from .security import Security, SecurityTypedDict
    from .simulation import Simulation, SimulationStatus, SimulationTypedDict
    from .simulationdetail import (
        SimulationDetail,
        SimulationDetailStatus,
        SimulationDetailTypedDict,
    )
    from .simulator import (
        Simulator,
        SimulatorSpecKind,
        SimulatorStatus,
        SimulatorTypedDict,
        Source,
    )
    from .simulatoractor import SimulatorActor, SimulatorActorTypedDict
    from .simulatorbuildprogress import (
        SimulatorBuildProgress,
        SimulatorBuildProgressLastSubmission,
        SimulatorBuildProgressModel,
        SimulatorBuildProgressPhase,
        SimulatorBuildProgressStage,
        SimulatorBuildProgressTypedDict,
    )
    from .simulatorerror import (
        SimulatorError,
        SimulatorErrorCode,
        SimulatorErrorReason,
        SimulatorErrorTypedDict,
    )
    from .specificationissue import (
        SpecificationIssue,
        SpecificationIssueKind,
        SpecificationIssueTypedDict,
    )
    from .specificationvalidation import (
        SpecificationValidation,
        SpecificationValidationTypedDict,
    )
    from .specificationwarning import (
        SpecificationWarning,
        SpecificationWarningCode,
        SpecificationWarningTypedDict,
    )
    from .start_simulationop import (
        StartSimulationRequest,
        StartSimulationRequestTypedDict,
        StartSimulationResponse,
        StartSimulationResponseTypedDict,
    )
    from .start_worldop import (
        StartWorldRequestRequest,
        StartWorldRequestRequestTypedDict,
    )
    from .startworldrequest import StartWorldRequest, StartWorldRequestTypedDict
    from .step import Step, StepKind, StepTypedDict
    from .stop_simulationop import StopSimulationRequest, StopSimulationRequestTypedDict
    from .stop_worldop import StopWorldRequest, StopWorldRequestTypedDict
    from .world import World, WorldStatus, WorldTypedDict
    from .worldbuildprogress import (
        WorldBuildProgress,
        WorldBuildProgressLastSubmission,
        WorldBuildProgressModel,
        WorldBuildProgressPhase,
        WorldBuildProgressStage,
        WorldBuildProgressTypedDict,
    )
    from .worlddatasummary import WorldDataSummary, WorldDataSummaryTypedDict
    from .worlderror import (
        WorldError,
        WorldErrorCode,
        WorldErrorReason,
        WorldErrorTypedDict,
    )
    from .worldrecordcount import WorldRecordCount, WorldRecordCountTypedDict
    from .worldsimulation import WorldSimulation, WorldSimulationTypedDict

__all__ = [
    "AdvanceSimulationRequest",
    "AdvanceSimulationRequestTypedDict",
    "AdvanceTimeRequest",
    "AdvanceTimeRequestTypedDict",
    "AdvanceWorldRequest",
    "AdvanceWorldRequestTypedDict",
    "BuildSimulatorRequest",
    "BuildSimulatorRequestModel",
    "BuildSimulatorRequestSpecKind",
    "BuildSimulatorRequestTypedDict",
    "BuildSimulatorResponse",
    "BuildSimulatorResponseTypedDict",
    "BuildWorldRequest",
    "BuildWorldRequestModel",
    "BuildWorldRequestTypedDict",
    "CancelSimulatorRequest",
    "CancelSimulatorRequestTypedDict",
    "CancelWorldRequest",
    "CancelWorldRequestTypedDict",
    "ClockAdvance",
    "ClockAdvanceMember",
    "ClockAdvanceMemberStatus",
    "ClockAdvanceMemberTypedDict",
    "ClockAdvanceStatus",
    "ClockAdvanceTypedDict",
    "ClockEvent",
    "ClockEventTypedDict",
    "CreateSimulationRequest",
    "CreateSimulationRequestTypedDict",
    "CreateSimulationResponse",
    "CreateSimulationResponseTypedDict",
    "CreatedSimulation",
    "CreatedSimulationStatus",
    "CreatedSimulationTypedDict",
    "CurrentSimulationToken",
    "CurrentSimulationTokenTypedDict",
    "DeleteSimulationRequest",
    "DeleteSimulationRequestTypedDict",
    "DeleteSimulatorRequest",
    "DeleteSimulatorRequestTypedDict",
    "DeleteWorldRequest",
    "DeleteWorldRequestTypedDict",
    "ForkSimulationRequest",
    "ForkSimulationRequestRequest",
    "ForkSimulationRequestRequestTypedDict",
    "ForkSimulationRequestTypedDict",
    "ForkSimulationResponse",
    "ForkSimulationResponseTypedDict",
    "GetSimulationAdvanceRequest",
    "GetSimulationAdvanceRequestTypedDict",
    "GetSimulationRequest",
    "GetSimulationRequestTypedDict",
    "GetSimulationTokenRequest",
    "GetSimulationTokenRequestTypedDict",
    "GetSimulationTokenResponse",
    "GetSimulationTokenResponseTypedDict",
    "GetSimulatorRequest",
    "GetSimulatorRequestTypedDict",
    "GetWorldAdvanceRequest",
    "GetWorldAdvanceRequestTypedDict",
    "GetWorldRequest",
    "GetWorldRequestTypedDict",
    "ListClockAdvanceEventsResponse",
    "ListClockAdvanceEventsResponseTypedDict",
    "ListSimulationAdvanceEventsRequest",
    "ListSimulationAdvanceEventsRequestTypedDict",
    "ListSimulationStepsRequest",
    "ListSimulationStepsRequestTypedDict",
    "ListSimulationStepsResponse",
    "ListSimulationStepsResponseTypedDict",
    "ListSimulationsRequest",
    "ListSimulationsRequestTypedDict",
    "ListSimulationsResponse",
    "ListSimulationsResponseTypedDict",
    "ListSimulationsStatus",
    "ListSimulatorsRequest",
    "ListSimulatorsRequestTypedDict",
    "ListSimulatorsResponse",
    "ListSimulatorsResponseTypedDict",
    "ListSimulatorsStatus",
    "ListWorldsRequest",
    "ListWorldsRequestTypedDict",
    "ListWorldsResponse",
    "ListWorldsResponseTypedDict",
    "ListWorldsStatus",
    "RegenerateSimulationTokenRequest",
    "RegenerateSimulationTokenRequestTypedDict",
    "RegenerateSimulationTokenResponse",
    "RegenerateSimulationTokenResponseTypedDict",
    "ResourceError",
    "ResourceErrorTypedDict",
    "Security",
    "SecurityTypedDict",
    "Simulation",
    "SimulationDetail",
    "SimulationDetailStatus",
    "SimulationDetailTypedDict",
    "SimulationStatus",
    "SimulationTypedDict",
    "Simulator",
    "SimulatorActor",
    "SimulatorActorTypedDict",
    "SimulatorBuildProgress",
    "SimulatorBuildProgressLastSubmission",
    "SimulatorBuildProgressModel",
    "SimulatorBuildProgressPhase",
    "SimulatorBuildProgressStage",
    "SimulatorBuildProgressTypedDict",
    "SimulatorError",
    "SimulatorErrorCode",
    "SimulatorErrorReason",
    "SimulatorErrorTypedDict",
    "SimulatorSpecKind",
    "SimulatorStatus",
    "SimulatorTypedDict",
    "SimulatorsBuildSimulatorRequest",
    "SimulatorsBuildSimulatorRequestTypedDict",
    "Source",
    "Spec",
    "SpecTypedDict",
    "SpecificationIssue",
    "SpecificationIssueKind",
    "SpecificationIssueTypedDict",
    "SpecificationValidation",
    "SpecificationValidationTypedDict",
    "SpecificationWarning",
    "SpecificationWarningCode",
    "SpecificationWarningTypedDict",
    "StartSimulationRequest",
    "StartSimulationRequestTypedDict",
    "StartSimulationResponse",
    "StartSimulationResponseTypedDict",
    "StartWorldRequest",
    "StartWorldRequestRequest",
    "StartWorldRequestRequestTypedDict",
    "StartWorldRequestTypedDict",
    "Step",
    "StepKind",
    "StepTypedDict",
    "StopSimulationRequest",
    "StopSimulationRequestTypedDict",
    "StopWorldRequest",
    "StopWorldRequestTypedDict",
    "World",
    "WorldBuildProgress",
    "WorldBuildProgressLastSubmission",
    "WorldBuildProgressModel",
    "WorldBuildProgressPhase",
    "WorldBuildProgressStage",
    "WorldBuildProgressTypedDict",
    "WorldDataSummary",
    "WorldDataSummaryTypedDict",
    "WorldError",
    "WorldErrorCode",
    "WorldErrorReason",
    "WorldErrorTypedDict",
    "WorldRecordCount",
    "WorldRecordCountTypedDict",
    "WorldSimulation",
    "WorldSimulationTypedDict",
    "WorldStatus",
    "WorldTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "AdvanceSimulationRequest": ".advance_simulationop",
    "AdvanceSimulationRequestTypedDict": ".advance_simulationop",
    "AdvanceWorldRequest": ".advance_worldop",
    "AdvanceWorldRequestTypedDict": ".advance_worldop",
    "AdvanceTimeRequest": ".advancetimerequest",
    "AdvanceTimeRequestTypedDict": ".advancetimerequest",
    "BuildSimulatorResponse": ".build_simulatorop",
    "BuildSimulatorResponseTypedDict": ".build_simulatorop",
    "SimulatorsBuildSimulatorRequest": ".build_simulatorop",
    "SimulatorsBuildSimulatorRequestTypedDict": ".build_simulatorop",
    "Spec": ".build_simulatorop",
    "SpecTypedDict": ".build_simulatorop",
    "BuildSimulatorRequest": ".buildsimulatorrequest",
    "BuildSimulatorRequestModel": ".buildsimulatorrequest",
    "BuildSimulatorRequestSpecKind": ".buildsimulatorrequest",
    "BuildSimulatorRequestTypedDict": ".buildsimulatorrequest",
    "BuildWorldRequest": ".buildworldrequest",
    "BuildWorldRequestModel": ".buildworldrequest",
    "BuildWorldRequestTypedDict": ".buildworldrequest",
    "CancelSimulatorRequest": ".cancel_simulatorop",
    "CancelSimulatorRequestTypedDict": ".cancel_simulatorop",
    "CancelWorldRequest": ".cancel_worldop",
    "CancelWorldRequestTypedDict": ".cancel_worldop",
    "ClockAdvance": ".clockadvance",
    "ClockAdvanceStatus": ".clockadvance",
    "ClockAdvanceTypedDict": ".clockadvance",
    "ClockAdvanceMember": ".clockadvancemember",
    "ClockAdvanceMemberStatus": ".clockadvancemember",
    "ClockAdvanceMemberTypedDict": ".clockadvancemember",
    "ClockEvent": ".clockevent",
    "ClockEventTypedDict": ".clockevent",
    "CreateSimulationResponse": ".create_simulationop",
    "CreateSimulationResponseTypedDict": ".create_simulationop",
    "CreatedSimulation": ".createdsimulation",
    "CreatedSimulationStatus": ".createdsimulation",
    "CreatedSimulationTypedDict": ".createdsimulation",
    "CreateSimulationRequest": ".createsimulationrequest",
    "CreateSimulationRequestTypedDict": ".createsimulationrequest",
    "CurrentSimulationToken": ".currentsimulationtoken",
    "CurrentSimulationTokenTypedDict": ".currentsimulationtoken",
    "DeleteSimulationRequest": ".delete_simulationop",
    "DeleteSimulationRequestTypedDict": ".delete_simulationop",
    "DeleteSimulatorRequest": ".delete_simulatorop",
    "DeleteSimulatorRequestTypedDict": ".delete_simulatorop",
    "DeleteWorldRequest": ".delete_worldop",
    "DeleteWorldRequestTypedDict": ".delete_worldop",
    "ForkSimulationRequestRequest": ".fork_simulationop",
    "ForkSimulationRequestRequestTypedDict": ".fork_simulationop",
    "ForkSimulationResponse": ".fork_simulationop",
    "ForkSimulationResponseTypedDict": ".fork_simulationop",
    "ForkSimulationRequest": ".forksimulationrequest",
    "ForkSimulationRequestTypedDict": ".forksimulationrequest",
    "GetSimulationAdvanceRequest": ".get_simulation_advanceop",
    "GetSimulationAdvanceRequestTypedDict": ".get_simulation_advanceop",
    "GetSimulationTokenRequest": ".get_simulation_tokenop",
    "GetSimulationTokenRequestTypedDict": ".get_simulation_tokenop",
    "GetSimulationTokenResponse": ".get_simulation_tokenop",
    "GetSimulationTokenResponseTypedDict": ".get_simulation_tokenop",
    "GetSimulationRequest": ".get_simulationop",
    "GetSimulationRequestTypedDict": ".get_simulationop",
    "GetSimulatorRequest": ".get_simulatorop",
    "GetSimulatorRequestTypedDict": ".get_simulatorop",
    "GetWorldAdvanceRequest": ".get_world_advanceop",
    "GetWorldAdvanceRequestTypedDict": ".get_world_advanceop",
    "GetWorldRequest": ".get_worldop",
    "GetWorldRequestTypedDict": ".get_worldop",
    "ListSimulationAdvanceEventsRequest": ".list_simulation_advance_eventsop",
    "ListSimulationAdvanceEventsRequestTypedDict": ".list_simulation_advance_eventsop",
    "ListSimulationStepsRequest": ".list_simulation_stepsop",
    "ListSimulationStepsRequestTypedDict": ".list_simulation_stepsop",
    "ListSimulationsRequest": ".list_simulationsop",
    "ListSimulationsRequestTypedDict": ".list_simulationsop",
    "ListSimulationsStatus": ".list_simulationsop",
    "ListSimulatorsRequest": ".list_simulatorsop",
    "ListSimulatorsRequestTypedDict": ".list_simulatorsop",
    "ListSimulatorsStatus": ".list_simulatorsop",
    "ListWorldsRequest": ".list_worldsop",
    "ListWorldsRequestTypedDict": ".list_worldsop",
    "ListWorldsStatus": ".list_worldsop",
    "ListClockAdvanceEventsResponse": ".listclockadvanceeventsresponse",
    "ListClockAdvanceEventsResponseTypedDict": ".listclockadvanceeventsresponse",
    "ListSimulationsResponse": ".listsimulationsresponse",
    "ListSimulationsResponseTypedDict": ".listsimulationsresponse",
    "ListSimulationStepsResponse": ".listsimulationstepsresponse",
    "ListSimulationStepsResponseTypedDict": ".listsimulationstepsresponse",
    "ListSimulatorsResponse": ".listsimulatorsresponse",
    "ListSimulatorsResponseTypedDict": ".listsimulatorsresponse",
    "ListWorldsResponse": ".listworldsresponse",
    "ListWorldsResponseTypedDict": ".listworldsresponse",
    "RegenerateSimulationTokenRequest": ".regenerate_simulation_tokenop",
    "RegenerateSimulationTokenRequestTypedDict": ".regenerate_simulation_tokenop",
    "RegenerateSimulationTokenResponse": ".regenerate_simulation_tokenop",
    "RegenerateSimulationTokenResponseTypedDict": ".regenerate_simulation_tokenop",
    "ResourceError": ".resourceerror",
    "ResourceErrorTypedDict": ".resourceerror",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "Simulation": ".simulation",
    "SimulationStatus": ".simulation",
    "SimulationTypedDict": ".simulation",
    "SimulationDetail": ".simulationdetail",
    "SimulationDetailStatus": ".simulationdetail",
    "SimulationDetailTypedDict": ".simulationdetail",
    "Simulator": ".simulator",
    "SimulatorSpecKind": ".simulator",
    "SimulatorStatus": ".simulator",
    "SimulatorTypedDict": ".simulator",
    "Source": ".simulator",
    "SimulatorActor": ".simulatoractor",
    "SimulatorActorTypedDict": ".simulatoractor",
    "SimulatorBuildProgress": ".simulatorbuildprogress",
    "SimulatorBuildProgressLastSubmission": ".simulatorbuildprogress",
    "SimulatorBuildProgressModel": ".simulatorbuildprogress",
    "SimulatorBuildProgressPhase": ".simulatorbuildprogress",
    "SimulatorBuildProgressStage": ".simulatorbuildprogress",
    "SimulatorBuildProgressTypedDict": ".simulatorbuildprogress",
    "SimulatorError": ".simulatorerror",
    "SimulatorErrorCode": ".simulatorerror",
    "SimulatorErrorReason": ".simulatorerror",
    "SimulatorErrorTypedDict": ".simulatorerror",
    "SpecificationIssue": ".specificationissue",
    "SpecificationIssueKind": ".specificationissue",
    "SpecificationIssueTypedDict": ".specificationissue",
    "SpecificationValidation": ".specificationvalidation",
    "SpecificationValidationTypedDict": ".specificationvalidation",
    "SpecificationWarning": ".specificationwarning",
    "SpecificationWarningCode": ".specificationwarning",
    "SpecificationWarningTypedDict": ".specificationwarning",
    "StartSimulationRequest": ".start_simulationop",
    "StartSimulationRequestTypedDict": ".start_simulationop",
    "StartSimulationResponse": ".start_simulationop",
    "StartSimulationResponseTypedDict": ".start_simulationop",
    "StartWorldRequestRequest": ".start_worldop",
    "StartWorldRequestRequestTypedDict": ".start_worldop",
    "StartWorldRequest": ".startworldrequest",
    "StartWorldRequestTypedDict": ".startworldrequest",
    "Step": ".step",
    "StepKind": ".step",
    "StepTypedDict": ".step",
    "StopSimulationRequest": ".stop_simulationop",
    "StopSimulationRequestTypedDict": ".stop_simulationop",
    "StopWorldRequest": ".stop_worldop",
    "StopWorldRequestTypedDict": ".stop_worldop",
    "World": ".world",
    "WorldStatus": ".world",
    "WorldTypedDict": ".world",
    "WorldBuildProgress": ".worldbuildprogress",
    "WorldBuildProgressLastSubmission": ".worldbuildprogress",
    "WorldBuildProgressModel": ".worldbuildprogress",
    "WorldBuildProgressPhase": ".worldbuildprogress",
    "WorldBuildProgressStage": ".worldbuildprogress",
    "WorldBuildProgressTypedDict": ".worldbuildprogress",
    "WorldDataSummary": ".worlddatasummary",
    "WorldDataSummaryTypedDict": ".worlddatasummary",
    "WorldError": ".worlderror",
    "WorldErrorCode": ".worlderror",
    "WorldErrorReason": ".worlderror",
    "WorldErrorTypedDict": ".worlderror",
    "WorldRecordCount": ".worldrecordcount",
    "WorldRecordCountTypedDict": ".worldrecordcount",
    "WorldSimulation": ".worldsimulation",
    "WorldSimulationTypedDict": ".worldsimulation",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
