"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .advancetimeinputbody import AdvanceTimeInputBody, AdvanceTimeInputBodyTypedDict
from continuous.types import BaseModel
from continuous.utils import (
    FieldMetadata,
    HeaderMetadata,
    PathParamMetadata,
    RequestMetadata,
)
import pydantic
from typing_extensions import Annotated, TypedDict


class AdvanceSimulationTimeRequestTypedDict(TypedDict):
    id: str
    r"""Simulation or World ID."""
    idempotency_key: str
    r"""Stable key for this request. Reuse with the same target returns the same operation."""
    body: AdvanceTimeInputBodyTypedDict


class AdvanceSimulationTimeRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Simulation or World ID."""

    idempotency_key: Annotated[
        str,
        pydantic.Field(alias="Idempotency-Key"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]
    r"""Stable key for this request. Reuse with the same target returns the same operation."""

    body: Annotated[
        AdvanceTimeInputBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
