"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel, UNSET_SENTINEL
from datetime import datetime
from pydantic import model_serializer
from typing import List, Literal, Optional
from typing_extensions import NotRequired, TypedDict


BuildWorldRequestBuilder = Literal[
    "openai",
    "claude",
]
r"""Model provider that builds starting data. Defaults to claude."""


class BuildWorldRequestTypedDict(TypedDict):
    simulators: List[str]
    r"""Simulator IDs for the World."""
    builder: NotRequired[BuildWorldRequestBuilder]
    r"""Model provider that builds starting data. Defaults to claude."""
    instructions: NotRequired[str]
    r"""Describe the initial data, scenario, and relationships. Populated Worlds support up to 8 selected Simulators and 1,000 starting records in total. Named record types replace their default data. At most 16,384 characters and 65,536 UTF-8 bytes. U+0000 is not permitted."""
    name: NotRequired[str]
    r"""Name for the World. Omission generates a name. The ID stays its identity, and names need not be unique."""
    start_time: NotRequired[datetime]
    r"""Simulated time the World starts at, in RFC 3339 format. Omission uses 2024-01-01T00:00:00Z. Saved starting data keeps its build dates."""
    timeout_seconds: NotRequired[int]
    r"""Time limit for generation and validation in seconds, from 1 to 72000. Defaults to 14400 (four hours). Excludes queue wait and finalization. Retries share the same deadline."""


class BuildWorldRequest(BaseModel):
    simulators: List[str]
    r"""Simulator IDs for the World."""

    builder: Optional[BuildWorldRequestBuilder] = "claude"
    r"""Model provider that builds starting data. Defaults to claude."""

    instructions: Optional[str] = None
    r"""Describe the initial data, scenario, and relationships. Populated Worlds support up to 8 selected Simulators and 1,000 starting records in total. Named record types replace their default data. At most 16,384 characters and 65,536 UTF-8 bytes. U+0000 is not permitted."""

    name: Optional[str] = None
    r"""Name for the World. Omission generates a name. The ID stays its identity, and names need not be unique."""

    start_time: Optional[datetime] = None
    r"""Simulated time the World starts at, in RFC 3339 format. Omission uses 2024-01-01T00:00:00Z. Saved starting data keeps its build dates."""

    timeout_seconds: Optional[int] = 14400
    r"""Time limit for generation and validation in seconds, from 1 to 72000. Defaults to 14400 (four hours). Excludes queue wait and finalization. Retries share the same deadline."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["builder", "instructions", "name", "start_time", "timeout_seconds"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
