"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


Builder = Literal[
    "openai",
    "claude",
]
r"""Builder provider. The default is claude."""


SpecKind = Literal[
    "openapi",
    "wsdl",
]
r"""Source specification format. Omission detects the format."""


class BuildSimulatorRequestTypedDict(TypedDict):
    builder: NotRequired[Builder]
    r"""Builder provider. The default is claude."""
    filter_: NotRequired[List[str]]
    r"""Optional operation filter regular expressions. Supply at most 64 expressions, with 1,024 characters in each expression. An empty list keeps all operations."""
    instructions: NotRequired[str]
    r"""Build guidance. At most 16,384 characters and 65,536 UTF-8 bytes. U+0000 is not permitted."""
    name: NotRequired[str]
    r"""Optional Simulator name. Names cannot start with smr_. Omission generates a name."""
    parent_id: NotRequired[str]
    r"""Stable parent Simulator ID for an incremental build."""
    spec_kind: NotRequired[SpecKind]
    r"""Source specification format. Omission detects the format."""


class BuildSimulatorRequest(BaseModel):
    builder: Optional[Builder] = "claude"
    r"""Builder provider. The default is claude."""

    filter_: Annotated[Optional[List[str]], pydantic.Field(alias="filter")] = None
    r"""Optional operation filter regular expressions. Supply at most 64 expressions, with 1,024 characters in each expression. An empty list keeps all operations."""

    instructions: Optional[str] = None
    r"""Build guidance. At most 16,384 characters and 65,536 UTF-8 bytes. U+0000 is not permitted."""

    name: Optional[str] = None
    r"""Optional Simulator name. Names cannot start with smr_. Omission generates a name."""

    parent_id: Optional[str] = None
    r"""Stable parent Simulator ID for an incremental build."""

    spec_kind: Optional[SpecKind] = None
    r"""Source specification format. Omission detects the format."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["builder", "filter", "instructions", "name", "parent_id", "spec_kind"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    BuildSimulatorRequest.model_rebuild()
except NameError:
    pass
