"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .buildsimulatorrequest import BuildSimulatorRequest, BuildSimulatorRequestTypedDict
from continuous.types import BaseModel, UNSET_SENTINEL
from continuous.utils import FieldMetadata, MultipartFormMetadata
import io
import pydantic
from pydantic import model_serializer
from typing import IO, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class SpecTypedDict(TypedDict):
    file_name: str
    content: Union[bytes, IO[bytes], io.IOBase]
    content_type: NotRequired[str]


class Spec(BaseModel):
    file_name: Annotated[
        str, pydantic.Field(alias="fileName"), FieldMetadata(multipart=True)
    ]

    content: Annotated[
        Union[bytes, IO[bytes], io.IOBase],
        pydantic.Field(alias=""),
        FieldMetadata(multipart=MultipartFormMetadata(content=True)),
    ]

    content_type: Annotated[
        Optional[str],
        pydantic.Field(alias="Content-Type"),
        FieldMetadata(multipart=True),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["contentType"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SimulatorsBuildSimulatorRequestTypedDict(TypedDict):
    request: BuildSimulatorRequestTypedDict
    spec: NotRequired[SpecTypedDict]
    r"""OpenAPI or WSDL file. A spec build sends it. At most 67,108,864 UTF-8 bytes."""


class SimulatorsBuildSimulatorRequest(BaseModel):
    request: Annotated[
        BuildSimulatorRequest, FieldMetadata(multipart=MultipartFormMetadata(json=True))
    ]

    spec: Annotated[
        Optional[Spec], FieldMetadata(multipart=MultipartFormMetadata(file=True))
    ] = None
    r"""OpenAPI or WSDL file. A spec build sends it. At most 67,108,864 UTF-8 bytes."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["spec"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
