"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


BuildSimulatorRequestBuilder = Literal[
    "openai",
    "claude",
]
r"""Model provider that builds the Simulator. Defaults to claude."""


SpecKind = Literal[
    "openapi",
    "wsdl",
]
r"""Source specification format. Omission detects the format."""


class BuildSimulatorRequestTypedDict(TypedDict):
    builder: NotRequired[BuildSimulatorRequestBuilder]
    r"""Model provider that builds the Simulator. Defaults to claude."""
    filter_: NotRequired[List[str]]
    r"""Regular expressions (RE2 syntax) that select the operations to implement. Each is matched against the OpenAPI operationId or the WSDL operation name; an operation is kept when any expression matches, and an OpenAPI operation without an operationId is dropped. At most 64 expressions of at most 1,024 characters each. Omit or send an empty list to keep every operation. Not allowed for an incremental build."""
    instructions: NotRequired[str]
    r"""Instructions for the builder. Required for an incremental build. At most 16,384 characters and 65,536 UTF-8 bytes; must not be blank or contain U+0000."""
    name: NotRequired[str]
    r"""Optional Simulator name. Names cannot start with smr_. Omission generates a name."""
    parent_id: NotRequired[str]
    r"""Parent Simulator ID. With instructions and no spec this starts an incremental build: the parent must be ready, and the request takes no filter or spec_kind."""
    spec_kind: NotRequired[SpecKind]
    r"""Source specification format. Omission detects the format."""


class BuildSimulatorRequest(BaseModel):
    builder: Optional[BuildSimulatorRequestBuilder] = "claude"
    r"""Model provider that builds the Simulator. Defaults to claude."""

    filter_: Annotated[Optional[List[str]], pydantic.Field(alias="filter")] = None
    r"""Regular expressions (RE2 syntax) that select the operations to implement. Each is matched against the OpenAPI operationId or the WSDL operation name; an operation is kept when any expression matches, and an OpenAPI operation without an operationId is dropped. At most 64 expressions of at most 1,024 characters each. Omit or send an empty list to keep every operation. Not allowed for an incremental build."""

    instructions: Optional[str] = None
    r"""Instructions for the builder. Required for an incremental build. At most 16,384 characters and 65,536 UTF-8 bytes; must not be blank or contain U+0000."""

    name: Optional[str] = None
    r"""Optional Simulator name. Names cannot start with smr_. Omission generates a name."""

    parent_id: Optional[str] = None
    r"""Parent Simulator ID. With instructions and no spec this starts an incremental build: the parent must be ready, and the request takes no filter or spec_kind."""

    spec_kind: Optional[SpecKind] = None
    r"""Source specification format. Omission detects the format."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["builder", "filter", "instructions", "name", "parent_id", "spec_kind"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    BuildSimulatorRequest.model_rebuild()
except NameError:
    pass
