"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel
from datetime import datetime
from typing_extensions import TypedDict


class BuildToolCallTypedDict(TypedDict):
    at: datetime
    r"""Time the call ran."""
    tool: str
    r"""Name of the tool. Arguments and output are private."""


class BuildToolCall(BaseModel):
    at: datetime
    r"""Time the call ran."""

    tool: str
    r"""Name of the tool. Arguments and output are private."""
