"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .resourceerror import ResourceError, ResourceErrorTypedDict
from continuous.types import BaseModel, Nullable, UNSET_SENTINEL, UnrecognizedStr
from pydantic import model_serializer
from typing import Literal, Union
from typing_extensions import TypedDict


ClockAdvanceMemberStatus = Union[
    Literal[
        "pending",
        "completed",
        "failed",
        "skipped",
    ],
    UnrecognizedStr,
]
r"""Whether this member is pending, committed, failed, or skipped because it is not running."""


class ClockAdvanceMemberTypedDict(TypedDict):
    error: Nullable[ResourceErrorTypedDict]
    event_count: int
    r"""Number of committed event executions."""
    simulation_id: str
    r"""Member Simulation ID."""
    status: ClockAdvanceMemberStatus
    r"""Whether this member is pending, committed, failed, or skipped because it is not running."""
    step: Nullable[int]
    r"""Committed local step, or null for no change or a failed advance."""


class ClockAdvanceMember(BaseModel):
    error: Nullable[ResourceError]

    event_count: int
    r"""Number of committed event executions."""

    simulation_id: str
    r"""Member Simulation ID."""

    status: ClockAdvanceMemberStatus
    r"""Whether this member is pending, committed, failed, or skipped because it is not running."""

    step: Nullable[int]
    r"""Committed local step, or null for no change or a failed advance."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
