"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .clockadvancemember import ClockAdvanceMember, ClockAdvanceMemberTypedDict
from .resourceerror import ResourceError, ResourceErrorTypedDict
from continuous.types import BaseModel, Nullable, UNSET_SENTINEL, UnrecognizedStr
from datetime import datetime
import pydantic
from pydantic import model_serializer
from typing import List, Literal, Union
from typing_extensions import Annotated, TypedDict


ClockAdvanceStatus = Union[
    Literal[
        "pending",
        "running",
        "completed",
        "failed",
    ],
    UnrecognizedStr,
]
r"""Durable operation state. Poll while pending or running."""


class ClockAdvanceTypedDict(TypedDict):
    error: Nullable[ResourceErrorTypedDict]
    event_count: int
    r"""Number of committed event executions."""
    from_: datetime
    r"""Clock before the requested advance."""
    id: str
    r"""Stable clock advance operation ID."""
    members: List[ClockAdvanceMemberTypedDict]
    r"""Progress for each participating Simulation."""
    status: ClockAdvanceStatus
    r"""Durable operation state. Poll while pending or running."""
    step: Nullable[int]
    r"""Committed local step, or null for no change or a World operation."""
    to: datetime
    r"""Requested absolute target time."""


class ClockAdvance(BaseModel):
    error: Nullable[ResourceError]

    event_count: int
    r"""Number of committed event executions."""

    from_: Annotated[datetime, pydantic.Field(alias="from")]
    r"""Clock before the requested advance."""

    id: str
    r"""Stable clock advance operation ID."""

    members: List[ClockAdvanceMember]
    r"""Progress for each participating Simulation."""

    status: ClockAdvanceStatus
    r"""Durable operation state. Poll while pending or running."""

    step: Nullable[int]
    r"""Committed local step, or null for no change or a World operation."""

    to: datetime
    r"""Requested absolute target time."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


try:
    ClockAdvance.model_rebuild()
except NameError:
    pass
