"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel
from datetime import datetime
from typing_extensions import TypedDict


class ClockEventTypedDict(TypedDict):
    at: datetime
    r"""Simulated time observed by this event handler."""
    event_id: str
    r"""Scheduled event ID."""
    sequence: int
    r"""Persisted insertion order for events due at the same time."""
    type: str
    r"""Declared event type."""


class ClockEvent(BaseModel):
    at: datetime
    r"""Simulated time observed by this event handler."""

    event_id: str
    r"""Scheduled event ID."""

    sequence: int
    r"""Persisted insertion order for events due at the same time."""

    type: str
    r"""Declared event type."""
