"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel
from typing_extensions import TypedDict


class CloneSimulatorResponseTypedDict(TypedDict):
    digest: str
    r"""OCI manifest digest, unchanged from the source."""
    id: str
    r"""New Simulator ID in the target workspace, or the same ID on an idempotent retry."""
    name: str
    r"""Display name of the clone."""
    workspace_id: str
    r"""Target workspace."""


class CloneSimulatorResponse(BaseModel):
    digest: str
    r"""OCI manifest digest, unchanged from the source."""

    id: str
    r"""New Simulator ID in the target workspace, or the same ID on an idempotent retry."""

    name: str
    r"""Display name of the clone."""

    workspace_id: str
    r"""Target workspace."""
