"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .clonesimulatorrequest import CloneSimulatorRequest, CloneSimulatorRequestTypedDict
from continuous.types import BaseModel
from continuous.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class CloneSimulatorRequestRequestTypedDict(TypedDict):
    id: str
    r"""Source Simulator ID."""
    body: CloneSimulatorRequestTypedDict


class CloneSimulatorRequestRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Source Simulator ID."""

    body: Annotated[
        CloneSimulatorRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
