"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CloneSimulatorRequestTypedDict(TypedDict):
    idempotency_key: str
    r"""Stable key for retrying this clone into the target workspace."""
    target_workspace_id: str
    r"""Workspace that receives the clone. It must differ from the source workspace."""
    name: NotRequired[str]
    r"""Display name for the clone. Defaults to the source Simulator's name."""


class CloneSimulatorRequest(BaseModel):
    idempotency_key: str
    r"""Stable key for retrying this clone into the target workspace."""

    target_workspace_id: str
    r"""Workspace that receives the clone. It must differ from the source workspace."""

    name: Optional[str] = None
    r"""Display name for the clone. Defaults to the source Simulator's name."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
