"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CreateCredentialRequestTypedDict(TypedDict):
    base_url: str
    r"""The https URL of the real system. Requests go to paths under it."""
    name: str
    r"""Credential name."""
    value: str
    r"""The full header value, for example Bearer followed by a token. The API never returns it."""
    header: NotRequired[str]
    r"""The HTTP header that carries the value."""


class CreateCredentialRequest(BaseModel):
    base_url: str
    r"""The https URL of the real system. Requests go to paths under it."""

    name: str
    r"""Credential name."""

    value: str
    r"""The full header value, for example Bearer followed by a token. The API never returns it."""

    header: Optional[str] = "Authorization"
    r"""The HTTP header that carries the value."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["header"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
