"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CreateSimulationRequestTypedDict(TypedDict):
    simulator_id: str
    r"""ID of the ready Simulator."""
    name: NotRequired[str]
    r"""Optional Simulation name. Omission generates a name."""


class CreateSimulationRequest(BaseModel):
    simulator_id: str
    r"""ID of the ready Simulator."""

    name: Optional[str] = None
    r"""Optional Simulation name. Omission generates a name."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
