"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel, Nullable, UNSET_SENTINEL, UnrecognizedStr
from datetime import datetime
import pydantic
from pydantic import model_serializer
from typing import Any, Literal, Union
from typing_extensions import Annotated, TypedDict


CreatedSimulationStatus = Union[
    Literal[
        "running",
        "paused",
        "stopped",
    ],
    UnrecognizedStr,
]
r"""Current status. running serves requests. paused means the Simulation was idle and the platform paused it; the next request wakes it. stopped means its state is saved and requests return 409 until you start it."""


class CreatedSimulationTypedDict(TypedDict):
    active_advance_id: Nullable[str]
    r"""Current clock advance operation ID, or null."""
    created_at: datetime
    r"""Simulation creation time."""
    current_time: datetime
    r"""Current simulated time."""
    endpoint: str
    r"""Base URL for requests to the Simulation."""
    expires_at: Nullable[datetime]
    r"""Always null; Simulation tokens do not expire. Deprecated; will be removed."""
    id: str
    r"""Simulation ID."""
    include_sample_data: bool
    r"""Whether the Simulation started with the Simulator's sample data. A fork inherits its source's state and reports false."""
    metadata: Any
    r"""Customer JSON metadata, or null."""
    name: str
    r"""Simulation name. The ID is its identity, and names need not be unique."""
    parent_id: Nullable[str]
    r"""Source Simulation ID for a fork, or null."""
    simulator_digest: str
    r"""OCI manifest digest pinned when the Simulation was created."""
    simulator_id: str
    r"""ID of the Simulator bound to this Simulation."""
    start_time: datetime
    r"""Initial simulated time."""
    status: CreatedSimulationStatus
    r"""Current status. running serves requests. paused means the Simulation was idle and the platform paused it; the next request wakes it. stopped means its state is saved and requests return 409 until you start it."""
    token: str
    r"""The Simulation's token for requests to its endpoint. It does not expire. Send it in the X-Continuous-Simulation-Token header, with an actor's id from GET /v1/simulations/{id} in X-Continuous-Actor to act as that caller. Retrieve it later with GET /v1/simulations/{id}/token."""


class CreatedSimulation(BaseModel):
    active_advance_id: Nullable[str]
    r"""Current clock advance operation ID, or null."""

    created_at: datetime
    r"""Simulation creation time."""

    current_time: datetime
    r"""Current simulated time."""

    endpoint: str
    r"""Base URL for requests to the Simulation."""

    expires_at: Annotated[
        Nullable[datetime],
        pydantic.Field(
            deprecated="warning: ** DEPRECATED ** - This will be removed in a future release, please migrate away from it as soon as possible."
        ),
    ]
    r"""Always null; Simulation tokens do not expire. Deprecated; will be removed."""

    id: str
    r"""Simulation ID."""

    include_sample_data: bool
    r"""Whether the Simulation started with the Simulator's sample data. A fork inherits its source's state and reports false."""

    metadata: Any
    r"""Customer JSON metadata, or null."""

    name: str
    r"""Simulation name. The ID is its identity, and names need not be unique."""

    parent_id: Nullable[str]
    r"""Source Simulation ID for a fork, or null."""

    simulator_digest: str
    r"""OCI manifest digest pinned when the Simulation was created."""

    simulator_id: str
    r"""ID of the Simulator bound to this Simulation."""

    start_time: datetime
    r"""Initial simulated time."""

    status: CreatedSimulationStatus
    r"""Current status. running serves requests. paused means the Simulation was idle and the platform paused it; the next request wakes it. stopped means its state is saved and requests return 409 until you start it."""

    token: str
    r"""The Simulation's token for requests to its endpoint. It does not expire. Send it in the X-Continuous-Simulation-Token header, with an actor's id from GET /v1/simulations/{id} in X-Continuous-Actor to act as that caller. Retrieve it later with GET /v1/simulations/{id}/token."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
