"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel, UNSET_SENTINEL
from datetime import datetime
from pydantic import model_serializer
from typing import Any, Optional
from typing_extensions import NotRequired, TypedDict


class CreateSimulationRequestTypedDict(TypedDict):
    simulator_id: str
    r"""ID of the ready Simulator."""
    metadata: NotRequired[Any]
    r"""Customer JSON metadata, up to 16 KiB and 64 nesting levels. Returned by create, get, and list. Omission uses null."""
    name: NotRequired[str]
    r"""Name for the Simulation. Omission generates a name. The ID stays its identity, and names need not be unique."""
    start_time: NotRequired[datetime]
    r"""Initial simulated time in RFC 3339 format. Omission uses 2024-01-01T00:00:00Z. Precision is milliseconds."""


class CreateSimulationRequest(BaseModel):
    simulator_id: str
    r"""ID of the ready Simulator."""

    metadata: Optional[Any] = None
    r"""Customer JSON metadata, up to 16 KiB and 64 nesting levels. Returned by create, get, and list. Omission uses null."""

    name: Optional[str] = None
    r"""Name for the Simulation. Omission generates a name. The ID stays its identity, and names need not be unique."""

    start_time: Optional[datetime] = None
    r"""Initial simulated time in RFC 3339 format. Omission uses 2024-01-01T00:00:00Z. Precision is milliseconds."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["metadata", "name", "start_time"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
