"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .createdsimulation import CreatedSimulation, CreatedSimulationTypedDict
from continuous.types import BaseModel
from typing import Dict, List
from typing_extensions import TypedDict


class CreateSimulationResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: CreatedSimulationTypedDict


class CreateSimulationResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: CreatedSimulation
