"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel, Nullable, UNSET_SENTINEL
from datetime import datetime
from pydantic import model_serializer
from typing_extensions import TypedDict


class CredentialTypedDict(TypedDict):
    base_url: Nullable[str]
    r"""The https URL of the real system, or null for a credential created without one. A build can use only a credential with a base URL."""
    created_at: datetime
    r"""Credential creation time."""
    header: str
    r"""The HTTP header that carries the value."""
    id: str
    r"""Credential ID."""
    name: str
    r"""Credential name. Names need not be unique."""


class Credential(BaseModel):
    base_url: Nullable[str]
    r"""The https URL of the real system, or null for a credential created without one. A build can use only a credential with a base URL."""

    created_at: datetime
    r"""Credential creation time."""

    header: str
    r"""The HTTP header that carries the value."""

    id: str
    r"""Credential ID."""

    name: str
    r"""Credential name. Names need not be unique."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
