"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .forksimulationrequest import ForkSimulationRequest, ForkSimulationRequestTypedDict
from continuous.types import BaseModel
from continuous.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class ForkSimulationRequestRequestTypedDict(TypedDict):
    id: str
    r"""Stable source Simulation ID."""
    body: ForkSimulationRequestTypedDict


class ForkSimulationRequestRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Stable source Simulation ID."""

    body: Annotated[
        ForkSimulationRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
