"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .createdsimulation import CreatedSimulation, CreatedSimulationTypedDict
from .forksimulationrequest import ForkSimulationRequest, ForkSimulationRequestTypedDict
from continuous.types import BaseModel
from continuous.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Dict, List
from typing_extensions import Annotated, TypedDict


class ForkSimulationRequestRequestTypedDict(TypedDict):
    id: str
    r"""Source Simulation ID."""
    body: ForkSimulationRequestTypedDict


class ForkSimulationRequestRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Source Simulation ID."""

    body: Annotated[
        ForkSimulationRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class ForkSimulationResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: CreatedSimulationTypedDict


class ForkSimulationResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: CreatedSimulation
