"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .currentsimulationtoken import (
    CurrentSimulationToken,
    CurrentSimulationTokenTypedDict,
)
from continuous.types import BaseModel
from continuous.utils import FieldMetadata, PathParamMetadata
from typing import Dict, List
from typing_extensions import Annotated, TypedDict


class GetSimulationTokenRequestTypedDict(TypedDict):
    id: str
    r"""Simulation ID."""


class GetSimulationTokenRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Simulation ID."""


class GetSimulationTokenResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: CurrentSimulationTokenTypedDict


class GetSimulationTokenResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: CurrentSimulationToken
