"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel
from continuous.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetWorldAdvanceRequestTypedDict(TypedDict):
    id: str
    r"""Simulation or World ID."""
    advance_id: str
    r"""Clock advance operation ID."""


class GetWorldAdvanceRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Simulation or World ID."""

    advance_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Clock advance operation ID."""
