"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class LimitationTypedDict(TypedDict):
    location: str
    r"""The operations the limitation affects, readably, or Simulator when it names none."""
    message: str
    r"""What the Simulator does differently from the real system."""
    operations: List[str]
    r"""Operation IDs the limitation affects, or empty when it names none."""
    reviewed: bool
    r"""Whether review confirmed that the pinned contract or the scaffold cannot express the correct behavior. False for a limitation the build recorded after review or that review did not confirm."""


class Limitation(BaseModel):
    location: str
    r"""The operations the limitation affects, readably, or Simulator when it names none."""

    message: str
    r"""What the Simulator does differently from the real system."""

    operations: List[str]
    r"""Operation IDs the limitation affects, or empty when it names none."""

    reviewed: bool
    r"""Whether review confirmed that the pinned contract or the scaffold cannot express the correct behavior. False for a limitation the build recorded after review or that review did not confirm."""
