"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel, UNSET_SENTINEL
from continuous.utils import FieldMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


ListSimulationsStatus = Literal[
    "running",
    "paused",
    "stopped",
]
r"""Optional lifecycle status filter."""


class ListSimulationsRequestTypedDict(TypedDict):
    status: NotRequired[ListSimulationsStatus]
    r"""Optional lifecycle status filter."""
    simulator_id: NotRequired[str]
    r"""Optional stable Simulator ID filter."""
    limit: NotRequired[int]
    r"""Page size. Values below 1 use 50. Values above 200 use 200."""
    cursor: NotRequired[str]
    r"""Opaque next_cursor value from a previous page."""


class ListSimulationsRequest(BaseModel):
    status: Annotated[
        Optional[ListSimulationsStatus],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""Optional lifecycle status filter."""

    simulator_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""Optional stable Simulator ID filter."""

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = 50
    r"""Page size. Values below 1 use 50. Values above 200 use 200."""

    cursor: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""Opaque next_cursor value from a previous page."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["status", "simulator_id", "limit", "cursor"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
