"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .simulation import Simulation, SimulationTypedDict
from continuous.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List
from typing_extensions import TypedDict


class ListSimulationsResponseTypedDict(TypedDict):
    next_cursor: Nullable[str]
    r"""Cursor for the next page, or null."""
    simulations: List[SimulationTypedDict]
    r"""Simulations in this page."""


class ListSimulationsResponse(BaseModel):
    next_cursor: Nullable[str]
    r"""Cursor for the next page, or null."""

    simulations: List[Simulation]
    r"""Simulations in this page."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
