"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .credential import Credential, CredentialTypedDict
from continuous.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List
from typing_extensions import TypedDict


class ListCredentialsResponseTypedDict(TypedDict):
    credentials: List[CredentialTypedDict]
    r"""Credential metadata in this page, newest first."""
    next_cursor: Nullable[str]
    r"""Cursor for the next page, or null."""


class ListCredentialsResponse(BaseModel):
    credentials: List[Credential]
    r"""Credential metadata in this page, newest first."""

    next_cursor: Nullable[str]
    r"""Cursor for the next page, or null."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
