"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel, UNSET_SENTINEL
from continuous.utils import FieldMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


ListSimulatorsStatus = Literal[
    "building",
    "ready",
    "failed",
    "canceled",
]
r"""Optional build status filter."""


class ListSimulatorsRequestTypedDict(TypedDict):
    status: NotRequired[ListSimulatorsStatus]
    r"""Optional build status filter."""
    name: NotRequired[str]
    r"""Optional exact Simulator name. Prefix a catalog name with continuous/. Names cannot start with smr_."""
    limit: NotRequired[int]
    r"""Page size. Values below 1 use 50. Values above 200 use 200."""
    cursor: NotRequired[str]
    r"""Opaque next_cursor value from a previous page."""


class ListSimulatorsRequest(BaseModel):
    status: Annotated[
        Optional[ListSimulatorsStatus],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""Optional build status filter."""

    name: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""Optional exact Simulator name. Prefix a catalog name with continuous/. Names cannot start with smr_."""

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = 50
    r"""Page size. Values below 1 use 50. Values above 200 use 200."""

    cursor: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""Opaque next_cursor value from a previous page."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["status", "name", "limit", "cursor"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
