"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .clockevent import ClockEvent, ClockEventTypedDict
from continuous.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List
from typing_extensions import TypedDict


class ListAdvanceEventsOutputBodyTypedDict(TypedDict):
    events: List[ClockEventTypedDict]
    r"""Committed events in execution order."""
    next_cursor: Nullable[str]
    r"""Cursor for the next page, or null."""


class ListAdvanceEventsOutputBody(BaseModel):
    events: List[ClockEvent]
    r"""Committed events in execution order."""

    next_cursor: Nullable[str]
    r"""Cursor for the next page, or null."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
