"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .mintsimulationtokenrequest import (
    MintSimulationTokenRequest,
    MintSimulationTokenRequestTypedDict,
)
from continuous.types import BaseModel
from continuous.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class MintSimulationTokenRequestRequestTypedDict(TypedDict):
    id: str
    r"""Simulation ID."""
    body: MintSimulationTokenRequestTypedDict


class MintSimulationTokenRequestRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Simulation ID."""

    body: Annotated[
        MintSimulationTokenRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
