"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel
from typing_extensions import TypedDict


class MintSimulationTokenRequestTypedDict(TypedDict):
    ttl_seconds: int
    r"""Accepted for compatibility, from 60 through 86,400. It does not change the token's lifetime."""


class MintSimulationTokenRequest(BaseModel):
    ttl_seconds: int
    r"""Accepted for compatibility, from 60 through 86,400. It does not change the token's lifetime."""
