"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .currentsimulationtoken import (
    CurrentSimulationToken,
    CurrentSimulationTokenTypedDict,
)
from continuous.types import BaseModel
from continuous.utils import FieldMetadata, HeaderMetadata, PathParamMetadata
import pydantic
from typing import Dict, List
from typing_extensions import Annotated, TypedDict


class RegenerateSimulationTokenRequestTypedDict(TypedDict):
    id: str
    r"""Simulation ID."""
    idempotency_key: str
    r"""Stable key for this regeneration request."""


class RegenerateSimulationTokenRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Simulation ID."""

    idempotency_key: Annotated[
        str,
        pydantic.Field(alias="Idempotency-Key"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]
    r"""Stable key for this regeneration request."""


class RegenerateSimulationTokenResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: CurrentSimulationTokenTypedDict


class RegenerateSimulationTokenResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: CurrentSimulationToken
