"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel
from typing_extensions import TypedDict


class ResourceErrorTypedDict(TypedDict):
    code: str
    r"""Stable machine-readable error code."""
    detail: str
    r"""Safe human-readable error detail."""


class ResourceError(BaseModel):
    code: str
    r"""Stable machine-readable error code."""

    detail: str
    r"""Safe human-readable error detail."""
