"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel, Nullable, UNSET_SENTINEL, UnrecognizedStr
from datetime import datetime
from pydantic import model_serializer
from typing import Literal, Union
from typing_extensions import TypedDict


SimulatorBuildProgressBuilder = Union[
    Literal[
        "claude",
        "openai",
    ],
    UnrecognizedStr,
]
r"""The coding-loop provider."""


LastSubmission = Union[
    Literal[
        "accepted",
        "rejected",
    ],
    UnrecognizedStr,
]
r"""Outcome of the most recent submit attempt, or null."""


SimulatorBuildProgressStage = Union[
    Literal[
        "derive",
        "build",
        "assemble",
    ],
    UnrecognizedStr,
]
r"""derive while the effective spec, build skeleton, and sandbox are prepared; build while the coding loop runs; assemble while an accepted artifact publishes."""


class SimulatorBuildProgressTypedDict(TypedDict):
    builder: SimulatorBuildProgressBuilder
    r"""The coding-loop provider."""
    last_submission: Nullable[LastSubmission]
    r"""Outcome of the most recent submit attempt, or null."""
    last_tool: Nullable[str]
    r"""Name of the most recent tool call, or null."""
    stage: SimulatorBuildProgressStage
    r"""derive while the effective spec, build skeleton, and sandbox are prepared; build while the coding loop runs; assemble while an accepted artifact publishes."""
    submissions: int
    r"""Submit attempts."""
    tool_calls: int
    r"""Tool calls the coding loop executed."""
    updated_at: datetime
    r"""Time of the last progress report."""


class SimulatorBuildProgress(BaseModel):
    builder: SimulatorBuildProgressBuilder
    r"""The coding-loop provider."""

    last_submission: Nullable[LastSubmission]
    r"""Outcome of the most recent submit attempt, or null."""

    last_tool: Nullable[str]
    r"""Name of the most recent tool call, or null."""

    stage: SimulatorBuildProgressStage
    r"""derive while the effective spec, build skeleton, and sandbox are prepared; build while the coding loop runs; assemble while an accepted artifact publishes."""

    submissions: int
    r"""Submit attempts."""

    tool_calls: int
    r"""Tool calls the coding loop executed."""

    updated_at: datetime
    r"""Time of the last progress report."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
