"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel
from datetime import datetime
from typing_extensions import TypedDict


class SimulationTokenTypedDict(TypedDict):
    expires_at: datetime
    r"""Token expiration time."""
    token: str
    r"""New data-plane token."""


class SimulationToken(BaseModel):
    expires_at: datetime
    r"""Token expiration time."""

    token: str
    r"""New data-plane token."""
