"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel
from typing_extensions import TypedDict


class SimulatorActorTypedDict(TypedDict):
    default: bool
    r"""Whether a request without the header acts as this caller."""
    entity: str
    r"""The entity whose row the id keys."""
    id: str
    r"""The value to send in the X-Continuous-Actor header: the key of the identity row the caller acts as."""
    name: str
    r"""The build's name for the caller."""
    role: str
    r"""The caller's role in the simulated service."""


class SimulatorActor(BaseModel):
    default: bool
    r"""Whether a request without the header acts as this caller."""

    entity: str
    r"""The entity whose row the id keys."""

    id: str
    r"""The value to send in the X-Continuous-Actor header: the key of the identity row the caller acts as."""

    name: str
    r"""The build's name for the caller."""

    role: str
    r"""The caller's role in the simulated service."""
