"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel, UnrecognizedStr
from typing import Literal, Union
from typing_extensions import TypedDict


SimulatorErrorCode = Union[
    Literal[
        "build_failed",
        "build_cancelled",
    ],
    UnrecognizedStr,
]
r"""Stable Simulator build error code."""


class SimulatorErrorTypedDict(TypedDict):
    code: SimulatorErrorCode
    r"""Stable Simulator build error code."""
    detail: str
    r"""Safe human-readable error detail."""


class SimulatorError(BaseModel):
    code: SimulatorErrorCode
    r"""Stable Simulator build error code."""

    detail: str
    r"""Safe human-readable error detail."""
