"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel, Nullable, UNSET_SENTINEL, UnrecognizedStr
from datetime import datetime
from pydantic import model_serializer
from typing import Literal, Union
from typing_extensions import TypedDict


SimulationStatus = Union[
    Literal[
        "running",
        "paused",
        "stopped",
    ],
    UnrecognizedStr,
]
r"""Current Simulation status."""


class SimulationTypedDict(TypedDict):
    created_at: datetime
    r"""Simulation creation time."""
    endpoint: str
    r"""Data-plane endpoint for the Simulation."""
    id: str
    r"""Stable Simulation ID."""
    name: str
    r"""Simulation name."""
    parent_id: Nullable[str]
    r"""Stable source Simulation ID for a fork, or null."""
    simulator_id: str
    r"""Stable ID of the Simulator."""
    status: SimulationStatus
    r"""Current Simulation status."""


class Simulation(BaseModel):
    created_at: datetime
    r"""Simulation creation time."""

    endpoint: str
    r"""Data-plane endpoint for the Simulation."""

    id: str
    r"""Stable Simulation ID."""

    name: str
    r"""Simulation name."""

    parent_id: Nullable[str]
    r"""Stable source Simulation ID for a fork, or null."""

    simulator_id: str
    r"""Stable ID of the Simulator."""

    status: SimulationStatus
    r"""Current Simulation status."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
