"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .simulatorbuildprogress import (
    SimulatorBuildProgress,
    SimulatorBuildProgressTypedDict,
)
from .simulatorerror import SimulatorError, SimulatorErrorTypedDict
from continuous.types import BaseModel, Nullable, UNSET_SENTINEL, UnrecognizedStr
from datetime import datetime
from pydantic import model_serializer
from typing import Literal, Union
from typing_extensions import TypedDict


Source = Union[
    Literal[
        "workspace",
        "catalog",
    ],
    UnrecognizedStr,
]
r"""workspace for a Simulator your workspace built; catalog for a read-only Simulator that Continuous publishes."""


SimulatorStatus = Union[
    Literal[
        "building",
        "ready",
        "failed",
        "canceled",
    ],
    UnrecognizedStr,
]
r"""building while the build runs; ready when Simulations, Worlds, and incremental builds can use it; failed when the build failed; canceled when a cancel request took effect."""


class SimulatorTypedDict(TypedDict):
    build: Nullable[SimulatorBuildProgressTypedDict]
    r"""The build's latest progress report, or null before the first report. A terminal Simulator keeps its last report."""
    created_at: datetime
    r"""Simulator creation time."""
    error: Nullable[SimulatorErrorTypedDict]
    id: str
    r"""Simulator ID."""
    name: str
    r"""Simulator name. Names cannot start with smr_."""
    parent_id: Nullable[str]
    r"""Parent Simulator ID, or null."""
    source: Source
    r"""workspace for a Simulator your workspace built; catalog for a read-only Simulator that Continuous publishes."""
    status: SimulatorStatus
    r"""building while the build runs; ready when Simulations, Worlds, and incremental builds can use it; failed when the build failed; canceled when a cancel request took effect."""


class Simulator(BaseModel):
    build: Nullable[SimulatorBuildProgress]
    r"""The build's latest progress report, or null before the first report. A terminal Simulator keeps its last report."""

    created_at: datetime
    r"""Simulator creation time."""

    error: Nullable[SimulatorError]

    id: str
    r"""Simulator ID."""

    name: str
    r"""Simulator name. Names cannot start with smr_."""

    parent_id: Nullable[str]
    r"""Parent Simulator ID, or null."""

    source: Source
    r"""workspace for a Simulator your workspace built; catalog for a read-only Simulator that Continuous publishes."""

    status: SimulatorStatus
    r"""building while the build runs; ready when Simulations, Worlds, and incremental builds can use it; failed when the build failed; canceled when a cancel request took effect."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
