"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .resourceerror import ResourceError, ResourceErrorTypedDict
from continuous.types import BaseModel, Nullable, UNSET_SENTINEL, UnrecognizedStr
from datetime import datetime
from pydantic import model_serializer
from typing import Literal, Union
from typing_extensions import TypedDict


Source = Union[
    Literal[
        "workspace",
        "catalog",
    ],
    UnrecognizedStr,
]
r"""Simulator source."""


SimulatorStatus = Union[
    Literal[
        "building",
        "ready",
        "failed",
        "canceled",
    ],
    UnrecognizedStr,
]
r"""Current build status."""


class SimulatorTypedDict(TypedDict):
    created_at: datetime
    r"""Simulator creation time."""
    error: Nullable[ResourceErrorTypedDict]
    id: str
    r"""Stable Simulator ID."""
    name: str
    r"""Simulator name. Names cannot start with smr_."""
    parent_id: Nullable[str]
    r"""Stable parent Simulator ID, or null."""
    source: Source
    r"""Simulator source."""
    status: SimulatorStatus
    r"""Current build status."""


class Simulator(BaseModel):
    created_at: datetime
    r"""Simulator creation time."""

    error: Nullable[ResourceError]

    id: str
    r"""Stable Simulator ID."""

    name: str
    r"""Simulator name. Names cannot start with smr_."""

    parent_id: Nullable[str]
    r"""Stable parent Simulator ID, or null."""

    source: Source
    r"""Simulator source."""

    status: SimulatorStatus
    r"""Current build status."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
