"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel
from datetime import datetime
from typing_extensions import TypedDict


class SimulationTokenTypedDict(TypedDict):
    expires_at: datetime
    r"""Token expiration time."""
    token: str
    r"""New token for requests to the Simulation endpoint. Send it in the X-Continuous-Simulation-Token header."""


class SimulationToken(BaseModel):
    expires_at: datetime
    r"""Token expiration time."""

    token: str
    r"""New token for requests to the Simulation endpoint. Send it in the X-Continuous-Simulation-Token header."""
