"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .specificationvalidation import (
    SpecificationValidation,
    SpecificationValidationTypedDict,
)
from continuous.types import BaseModel, Nullable, UNSET_SENTINEL, UnrecognizedStr
from pydantic import model_serializer
from typing import Literal, Union
from typing_extensions import TypedDict


SimulatorErrorCode = Union[
    Literal[
        "build_failed",
        "build_cancelled",
        "specification_validation_failed",
    ],
    UnrecognizedStr,
]
r"""Stable Simulator build error code."""


SimulatorErrorReason = Union[
    Literal[
        "canceled",
        "specification_invalid",
        "time_limit",
        "service_unavailable",
        "build_failed",
        "population_unsupported",
        "world_start_failed",
        "world_operation_failed",
    ],
    UnrecognizedStr,
]
r"""Bounded failure reason for selecting recovery guidance, or null when unavailable. Older servers can omit this field."""


class SimulatorErrorTypedDict(TypedDict):
    agent_message: Nullable[str]
    r"""Plain-text explanation from the build agent, when it could not continue. At most 4096 UTF-8 bytes."""
    code: SimulatorErrorCode
    r"""Stable Simulator build error code."""
    detail: str
    r"""Safe human-readable error detail."""
    reason: Nullable[SimulatorErrorReason]
    r"""Bounded failure reason for selecting recovery guidance, or null when unavailable. Older servers can omit this field."""
    validation: Nullable[SpecificationValidationTypedDict]


class SimulatorError(BaseModel):
    agent_message: Nullable[str]
    r"""Plain-text explanation from the build agent, when it could not continue. At most 4096 UTF-8 bytes."""

    code: SimulatorErrorCode
    r"""Stable Simulator build error code."""

    detail: str
    r"""Safe human-readable error detail."""

    reason: Nullable[SimulatorErrorReason]
    r"""Bounded failure reason for selecting recovery guidance, or null when unavailable. Older servers can omit this field."""

    validation: Nullable[SpecificationValidation]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
