"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .limitation import Limitation, LimitationTypedDict
from .specificationwarning import SpecificationWarning, SpecificationWarningTypedDict
from continuous.types import BaseModel, Nullable, UNSET_SENTINEL, UnrecognizedStr
from pydantic import model_serializer
from typing import List, Literal, Union
from typing_extensions import TypedDict


SimulatorBuildProgressLastSubmission = Union[
    Literal[
        "accepted",
        "rejected",
    ],
    UnrecognizedStr,
]
r"""Outcome of the most recent submit attempt, or null."""


SimulatorBuildProgressModel = Union[
    Literal[
        "gpt-6-astra",
        "gpt-6.1-sol",
        "claude-opus-5-5",
        "claude-fable-5-1",
        "gpt-6-sol",
    ],
    UnrecognizedStr,
]
r"""The model the builder and reviewer run on. A build recorded before model selection reports its provider's default."""


SimulatorBuildProgressPhase = Union[
    Literal[
        "build",
        "review",
        "finalize",
    ],
    UnrecognizedStr,
]
r"""Agent phase: build for generation, review for the separate reviewer, finalize for author repair after review. Null when not recorded."""


SimulatorBuildProgressStage = Union[
    Literal[
        "derive",
        "build",
        "assemble",
    ],
    UnrecognizedStr,
]
r"""derive while the effective spec, build skeleton, and sandbox are prepared; build while the coding loop runs; assemble while an accepted artifact publishes."""


class SimulatorBuildProgressTypedDict(TypedDict):
    hidden_limitations: int
    r"""Limitations the accepted build records beyond those listed in limitations."""
    last_submission: Nullable[SimulatorBuildProgressLastSubmission]
    r"""Outcome of the most recent submit attempt, or null."""
    last_tool: Nullable[str]
    r"""Name of the most recent tool call, or null. Tool arguments and output are private."""
    limitations: List[LimitationTypedDict]
    r"""Behavior the accepted build does not serve like the real system, most important first, set when the build is accepted. Empty when none."""
    model: SimulatorBuildProgressModel
    r"""The model the builder and reviewer run on. A build recorded before model selection reports its provider's default."""
    phase: Nullable[SimulatorBuildProgressPhase]
    r"""Agent phase: build for generation, review for the separate reviewer, finalize for author repair after review. Null when not recorded."""
    stage: SimulatorBuildProgressStage
    r"""derive while the effective spec, build skeleton, and sandbox are prepared; build while the coding loop runs; assemble while an accepted artifact publishes."""
    submissions: int
    r"""Submit attempts."""
    tool_calls: int
    r"""Tool calls the coding loop executed."""
    warnings: List[SpecificationWarningTypedDict]
    r"""Specification defects the build tolerated without changing the specification, set when the build prepares its specification. Empty when none."""


class SimulatorBuildProgress(BaseModel):
    hidden_limitations: int
    r"""Limitations the accepted build records beyond those listed in limitations."""

    last_submission: Nullable[SimulatorBuildProgressLastSubmission]
    r"""Outcome of the most recent submit attempt, or null."""

    last_tool: Nullable[str]
    r"""Name of the most recent tool call, or null. Tool arguments and output are private."""

    limitations: List[Limitation]
    r"""Behavior the accepted build does not serve like the real system, most important first, set when the build is accepted. Empty when none."""

    model: SimulatorBuildProgressModel
    r"""The model the builder and reviewer run on. A build recorded before model selection reports its provider's default."""

    phase: Nullable[SimulatorBuildProgressPhase]
    r"""Agent phase: build for generation, review for the separate reviewer, finalize for author repair after review. Null when not recorded."""

    stage: SimulatorBuildProgressStage
    r"""derive while the effective spec, build skeleton, and sandbox are prepared; build while the coding loop runs; assemble while an accepted artifact publishes."""

    submissions: int
    r"""Submit attempts."""

    tool_calls: int
    r"""Tool calls the coding loop executed."""

    warnings: List[SpecificationWarning]
    r"""Specification defects the build tolerated without changing the specification, set when the build prepares its specification. Empty when none."""

    @model_serializer(mode="wrap")
    def _serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
