"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .buildtoolcall import BuildToolCall, BuildToolCallTypedDict
from continuous.types import BaseModel, Nullable, UNSET_SENTINEL, UnrecognizedStr
from datetime import datetime
from pydantic import model_serializer
from typing import List, Literal, Union
from typing_extensions import TypedDict


SimulatorBuildProgressLastSubmission = Union[
    Literal[
        "accepted",
        "rejected",
    ],
    UnrecognizedStr,
]
r"""Outcome of the most recent submit attempt, or null."""


SimulatorBuildProgressModel = Union[
    Literal[
        "gpt-6-astra",
        "gpt-6-sol",
        "claude-opus-5-5",
        "claude-fable-5-1",
    ],
    UnrecognizedStr,
]
r"""The model the builder and reviewer run on. A build recorded before model selection reports its provider's default."""


SimulatorBuildProgressPhase = Union[
    Literal[
        "build",
        "review",
        "finalize",
    ],
    UnrecognizedStr,
]
r"""Agent phase: build for generation, review for the separate reviewer, finalize for author repair after review. Null when not recorded."""


SimulatorBuildProgressStage = Union[
    Literal[
        "derive",
        "build",
        "assemble",
    ],
    UnrecognizedStr,
]
r"""derive while the effective spec, build skeleton, and sandbox are prepared; build while the coding loop runs; assemble while an accepted artifact publishes."""


class SimulatorBuildProgressTypedDict(TypedDict):
    last_submission: Nullable[SimulatorBuildProgressLastSubmission]
    r"""Outcome of the most recent submit attempt, or null."""
    last_tool: Nullable[str]
    r"""Name of the most recent tool call, or null."""
    model: SimulatorBuildProgressModel
    r"""The model the builder and reviewer run on. A build recorded before model selection reports its provider's default."""
    phase: Nullable[SimulatorBuildProgressPhase]
    r"""Agent phase: build for generation, review for the separate reviewer, finalize for author repair after review. Null when not recorded."""
    recent_tools: List[BuildToolCallTypedDict]
    r"""The most recent tool calls, oldest first, at most 20."""
    stage: SimulatorBuildProgressStage
    r"""derive while the effective spec, build skeleton, and sandbox are prepared; build while the coding loop runs; assemble while an accepted artifact publishes."""
    submissions: int
    r"""Submit attempts."""
    tool_calls: int
    r"""Tool calls the coding loop executed."""
    updated_at: datetime
    r"""Time of the last progress report."""


class SimulatorBuildProgress(BaseModel):
    last_submission: Nullable[SimulatorBuildProgressLastSubmission]
    r"""Outcome of the most recent submit attempt, or null."""

    last_tool: Nullable[str]
    r"""Name of the most recent tool call, or null."""

    model: SimulatorBuildProgressModel
    r"""The model the builder and reviewer run on. A build recorded before model selection reports its provider's default."""

    phase: Nullable[SimulatorBuildProgressPhase]
    r"""Agent phase: build for generation, review for the separate reviewer, finalize for author repair after review. Null when not recorded."""

    recent_tools: List[BuildToolCall]
    r"""The most recent tool calls, oldest first, at most 20."""

    stage: SimulatorBuildProgressStage
    r"""derive while the effective spec, build skeleton, and sandbox are prepared; build while the coding loop runs; assemble while an accepted artifact publishes."""

    submissions: int
    r"""Submit attempts."""

    tool_calls: int
    r"""Tool calls the coding loop executed."""

    updated_at: datetime
    r"""Time of the last progress report."""

    @model_serializer(mode="wrap")
    def _serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
