"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel, Nullable, UNSET_SENTINEL, UnrecognizedStr
from datetime import datetime
from pydantic import model_serializer
from typing import Literal, Union
from typing_extensions import TypedDict


SimulationStatus = Union[
    Literal[
        "running",
        "paused",
        "stopped",
    ],
    UnrecognizedStr,
]
r"""Current status. running serves requests. paused means the Simulation was idle and the platform paused it; the next request wakes it. stopped means its state is saved and requests return 409 until you start it."""


class SimulationTypedDict(TypedDict):
    active_advance_id: Nullable[str]
    r"""Current clock advance operation ID, or null."""
    created_at: datetime
    r"""Simulation creation time."""
    current_time: datetime
    r"""Current simulated time."""
    endpoint: str
    r"""Base URL for requests to the Simulation."""
    id: str
    r"""Simulation ID."""
    name: str
    r"""Simulation name. The ID is its identity, and names need not be unique."""
    parent_id: Nullable[str]
    r"""Source Simulation ID for a fork, or null."""
    simulator_digest: str
    r"""OCI manifest digest pinned when the Simulation was created."""
    simulator_id: str
    r"""ID of the Simulator bound to this Simulation."""
    start_time: datetime
    r"""Initial simulated time."""
    status: SimulationStatus
    r"""Current status. running serves requests. paused means the Simulation was idle and the platform paused it; the next request wakes it. stopped means its state is saved and requests return 409 until you start it."""


class Simulation(BaseModel):
    active_advance_id: Nullable[str]
    r"""Current clock advance operation ID, or null."""

    created_at: datetime
    r"""Simulation creation time."""

    current_time: datetime
    r"""Current simulated time."""

    endpoint: str
    r"""Base URL for requests to the Simulation."""

    id: str
    r"""Simulation ID."""

    name: str
    r"""Simulation name. The ID is its identity, and names need not be unique."""

    parent_id: Nullable[str]
    r"""Source Simulation ID for a fork, or null."""

    simulator_digest: str
    r"""OCI manifest digest pinned when the Simulation was created."""

    simulator_id: str
    r"""ID of the Simulator bound to this Simulation."""

    start_time: datetime
    r"""Initial simulated time."""

    status: SimulationStatus
    r"""Current status. running serves requests. paused means the Simulation was idle and the platform paused it; the next request wakes it. stopped means its state is saved and requests return 409 until you start it."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
