"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel, UnrecognizedStr
from typing import List, Literal, Union
from typing_extensions import TypedDict


SpecificationWarningCode = Union[
    Literal[
        "spec.enum_duplicate",
        "spec.path_parameter_optional",
        "spec.default_invalid",
        "spec.response_untyped",
        "spec.schema_limit",
        "spec.operation_unservable",
        "spec.example_null",
    ],
    UnrecognizedStr,
]
r"""Stable warning code."""


class SpecificationWarningTypedDict(TypedDict):
    code: SpecificationWarningCode
    r"""Stable warning code."""
    location: str
    r"""Readable endpoint or field affected by this warning."""
    message: str
    r"""What the specification declares and how the build handles it."""
    operations: List[str]
    r"""Always empty."""


class SpecificationWarning(BaseModel):
    code: SpecificationWarningCode
    r"""Stable warning code."""

    location: str
    r"""Readable endpoint or field affected by this warning."""

    message: str
    r"""What the specification declares and how the build handles it."""

    operations: List[str]
    r"""Always empty."""
