"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel, UnrecognizedStr
from typing import Literal, Union
from typing_extensions import TypedDict


SpecificationIssueKind = Union[
    Literal[
        "invalid",
        "unsupported",
        "incomplete",
        "unknown",
    ],
    UnrecognizedStr,
]
r"""Whether the input is invalid, unsupported, incomplete, or has no specific diagnosis."""


class SpecificationIssueTypedDict(TypedDict):
    code: str
    r"""Stable validation rule code."""
    kind: SpecificationIssueKind
    r"""Whether the input is invalid, unsupported, incomplete, or has no specific diagnosis."""
    message: str
    r"""What needs attention at this location."""
    operation: str
    r"""Affected operation ID or method and path, when available. Empty for document-level issues."""
    path: str
    r"""Location in the submitted specification, as a JSON pointer or XML path."""
    suggestion: str
    r"""How to correct or address the problem."""


class SpecificationIssue(BaseModel):
    code: str
    r"""Stable validation rule code."""

    kind: SpecificationIssueKind
    r"""Whether the input is invalid, unsupported, incomplete, or has no specific diagnosis."""

    message: str
    r"""What needs attention at this location."""

    operation: str
    r"""Affected operation ID or method and path, when available. Empty for document-level issues."""

    path: str
    r"""Location in the submitted specification, as a JSON pointer or XML path."""

    suggestion: str
    r"""How to correct or address the problem."""
