"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .specificationissue import SpecificationIssue, SpecificationIssueTypedDict
from continuous.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class SpecificationValidationTypedDict(TypedDict):
    issues: List[SpecificationIssueTypedDict]
    r"""Specification validation problems. At most 20 are returned."""


class SpecificationValidation(BaseModel):
    issues: List[SpecificationIssue]
    r"""Specification validation problems. At most 20 are returned."""
