"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel, UnrecognizedStr
from typing import List, Literal, Union
from typing_extensions import TypedDict


SpecificationWarningCode = Union[
    Literal[
        "spec.enum_duplicate",
        "spec.path_parameter_optional",
        "spec.default_invalid",
        "spec.response_untyped",
        "spec.schema_limit",
        "spec.operation_unservable",
        "spec.version_ambiguous",
        "spec.example_null",
        "build.limitation",
        "build.unrepaired",
    ],
    UnrecognizedStr,
]
r"""Stable warning code. build.limitation marks behavior the Simulator does not serve like the real system. build.unrepaired marks such behavior that review did not mark a limit of the pinned contract or the scaffold, or that the build declared after review."""


class SpecificationWarningTypedDict(TypedDict):
    code: SpecificationWarningCode
    r"""Stable warning code. build.limitation marks behavior the Simulator does not serve like the real system. build.unrepaired marks such behavior that review did not mark a limit of the pinned contract or the scaffold, or that the build declared after review."""
    location: str
    r"""Readable endpoint or field affected by this warning, or the affected operations for a limitation."""
    message: str
    r"""What the specification declares and how the build handles it, or what the limitation is."""
    operations: List[str]
    r"""Operation IDs a limitation affects, or empty when the warning names none."""


class SpecificationWarning(BaseModel):
    code: SpecificationWarningCode
    r"""Stable warning code. build.limitation marks behavior the Simulator does not serve like the real system. build.unrepaired marks such behavior that review did not mark a limit of the pinned contract or the scaffold, or that the build declared after review."""

    location: str
    r"""Readable endpoint or field affected by this warning, or the affected operations for a limitation."""

    message: str
    r"""What the specification declares and how the build handles it, or what the limitation is."""

    operations: List[str]
    r"""Operation IDs a limitation affects, or empty when the warning names none."""
