"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel
from typing_extensions import TypedDict


class StepTypedDict(TypedDict):
    label: str
    r"""HTTP method and path of the request that produced this step, without the query string, for example POST /v1/widgets."""
    step: int
    r"""Step number. Use it as at_step when you fork."""


class Step(BaseModel):
    label: str
    r"""HTTP method and path of the request that produced this step, without the query string, for example POST /v1/widgets."""

    step: int
    r"""Step number. Use it as at_step when you fork."""
