"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel
from typing_extensions import TypedDict


class StepTypedDict(TypedDict):
    label: str
    r"""Request label. It usually contains the HTTP method and path."""
    step: int
    r"""Completed request number. Use this value as at_step when you fork the Simulation."""


class Step(BaseModel):
    label: str
    r"""Request label. It usually contains the HTTP method and path."""

    step: int
    r"""Completed request number. Use this value as at_step when you fork the Simulation."""
