"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel, Nullable, UNSET_SENTINEL, UnrecognizedStr
from datetime import datetime
from pydantic import model_serializer
from typing import Literal, Union
from typing_extensions import TypedDict


Kind = Union[
    Literal[
        "api",
        "advance",
    ],
    UnrecognizedStr,
]
r"""api for an API write or advance for a clock advance."""


class StepTypedDict(TypedDict):
    advance_id: Nullable[str]
    r"""Advance that produced this step, if any."""
    kind: Kind
    r"""api for an API write or advance for a clock advance."""
    label: str
    r"""HTTP method and path of the request that produced this step, without the query string, for example POST /v1/widgets."""
    step: int
    r"""Step number. Use it as at_step when you fork."""
    time_after: Nullable[datetime]
    r"""Clock after the step."""
    time_before: Nullable[datetime]
    r"""Clock before the step."""


class Step(BaseModel):
    advance_id: Nullable[str]
    r"""Advance that produced this step, if any."""

    kind: Kind
    r"""api for an API write or advance for a clock advance."""

    label: str
    r"""HTTP method and path of the request that produced this step, without the query string, for example POST /v1/widgets."""

    step: int
    r"""Step number. Use it as at_step when you fork."""

    time_after: Nullable[datetime]
    r"""Clock after the step."""

    time_before: Nullable[datetime]
    r"""Clock before the step."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
