"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .updatecredentialrequest import (
    UpdateCredentialRequest,
    UpdateCredentialRequestTypedDict,
)
from continuous.types import BaseModel
from continuous.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateCredentialRequestRequestTypedDict(TypedDict):
    id: str
    r"""Credential ID."""
    body: UpdateCredentialRequestTypedDict


class UpdateCredentialRequestRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Credential ID."""

    body: Annotated[
        UpdateCredentialRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
