"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class UpdateCredentialRequestTypedDict(TypedDict):
    base_url: NotRequired[str]
    r"""New https URL of the real system."""
    header: NotRequired[str]
    r"""New HTTP header that carries the value."""
    name: NotRequired[str]
    r"""New credential name."""
    value: NotRequired[str]
    r"""New full header value. Required when base_url or header changes. Builds that start an agent after the change use it. The API never returns it."""


class UpdateCredentialRequest(BaseModel):
    base_url: Optional[str] = None
    r"""New https URL of the real system."""

    header: Optional[str] = None
    r"""New HTTP header that carries the value."""

    name: Optional[str] = None
    r"""New credential name."""

    value: Optional[str] = None
    r"""New full header value. Required when base_url or header changes. Builds that start an agent after the change use it. The API never returns it."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["base_url", "header", "name", "value"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
