"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .buildtoolcall import BuildToolCall, BuildToolCallTypedDict
from .worlddatasummary import WorldDataSummary, WorldDataSummaryTypedDict
from continuous.types import BaseModel, Nullable, UNSET_SENTINEL, UnrecognizedStr
from pydantic import model_serializer
from typing import List, Literal, Union
from typing_extensions import TypedDict


WorldBuildProgressBuilder = Union[
    Literal[
        "openai",
        "claude",
    ],
    UnrecognizedStr,
]
r"""Selected model provider, or null for a build created before provider selection."""


WorldBuildProgressLastSubmission = Union[
    Literal[
        "accepted",
        "rejected",
    ],
    UnrecognizedStr,
]
r"""Outcome of the most recent plan submission, or null."""


WorldBuildProgressStage = Union[
    Literal[
        "planning",
        "generating",
        "validating",
        "complete",
    ],
    UnrecognizedStr,
]
r"""Current phase of starting-data preparation."""


class WorldBuildProgressTypedDict(TypedDict):
    builder: Nullable[WorldBuildProgressBuilder]
    r"""Selected model provider, or null for a build created before provider selection."""
    last_submission: Nullable[WorldBuildProgressLastSubmission]
    r"""Outcome of the most recent plan submission, or null."""
    last_tool: Nullable[str]
    r"""Name of the most recent tool, or null. Tool arguments and output are private."""
    recent_tools: List[BuildToolCallTypedDict]
    r"""The most recent tool calls, oldest first, at most 20."""
    stage: WorldBuildProgressStage
    r"""Current phase of starting-data preparation."""
    submissions: int
    r"""Number of submitted starting-data plans."""
    summary: Nullable[WorldDataSummaryTypedDict]
    r"""Verified starting data, or null before a completed build."""
    tool_calls: int
    r"""Number of agent tool calls."""


class WorldBuildProgress(BaseModel):
    builder: Nullable[WorldBuildProgressBuilder]
    r"""Selected model provider, or null for a build created before provider selection."""

    last_submission: Nullable[WorldBuildProgressLastSubmission]
    r"""Outcome of the most recent plan submission, or null."""

    last_tool: Nullable[str]
    r"""Name of the most recent tool, or null. Tool arguments and output are private."""

    recent_tools: List[BuildToolCall]
    r"""The most recent tool calls, oldest first, at most 20."""

    stage: WorldBuildProgressStage
    r"""Current phase of starting-data preparation."""

    submissions: int
    r"""Number of submitted starting-data plans."""

    summary: Nullable[WorldDataSummary]
    r"""Verified starting data, or null before a completed build."""

    tool_calls: int
    r"""Number of agent tool calls."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
