"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .worldbuild import WorldBuild, WorldBuildTypedDict
from .worlderror import WorldError, WorldErrorTypedDict
from .worldsimulation import WorldSimulation, WorldSimulationTypedDict
from continuous.types import BaseModel, Nullable, UNSET_SENTINEL, UnrecognizedStr
from datetime import datetime
from pydantic import model_serializer
from typing import List, Literal, Optional, Union
from typing_extensions import NotRequired, TypedDict


WorldStatus = Union[
    Literal[
        "building",
        "ready",
        "running",
        "stopped",
        "failed",
        "canceled",
    ],
    UnrecognizedStr,
]
r"""building while the build runs; ready when it can be started; running or stopped once its Simulations exist; failed when building or first start fails; canceled when the build was canceled."""


class WorldTypedDict(TypedDict):
    created_at: datetime
    r"""Time when the World build started."""
    error: Nullable[WorldErrorTypedDict]
    id: str
    r"""World ID."""
    instructions: str
    r"""Instructions for the initial synthetic data and relationships."""
    simulations: List[WorldSimulationTypedDict]
    r"""Created member Simulations. This list is empty before first start."""
    simulators: List[str]
    r"""Simulator IDs in member order."""
    status: WorldStatus
    r"""building while the build runs; ready when it can be started; running or stopped once its Simulations exist; failed when building or first start fails; canceled when the build was canceled."""
    build: NotRequired[WorldBuildTypedDict]


class World(BaseModel):
    created_at: datetime
    r"""Time when the World build started."""

    error: Nullable[WorldError]

    id: str
    r"""World ID."""

    instructions: str
    r"""Instructions for the initial synthetic data and relationships."""

    simulations: List[WorldSimulation]
    r"""Created member Simulations. This list is empty before first start."""

    simulators: List[str]
    r"""Simulator IDs in member order."""

    status: WorldStatus
    r"""building while the build runs; ready when it can be started; running or stopped once its Simulations exist; failed when building or first start fails; canceled when the build was canceled."""

    build: Optional[WorldBuild] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["build"])
        nullable_fields = set(["error"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
