"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel, Nullable, UNSET_SENTINEL, UnrecognizedStr
from pydantic import model_serializer
from typing import Literal, Union
from typing_extensions import TypedDict


WorldErrorCode = Union[
    Literal[
        "world_build_canceled",
        "world_start_failed",
        "world_create_failed",
        "world_failed",
        "world_population_failed",
        "world_population_unsupported",
        "world_population_invalid",
        "world_population_unavailable",
    ],
    UnrecognizedStr,
]
r"""Stable World error code."""


WorldErrorReason = Union[
    Literal[
        "canceled",
        "specification_invalid",
        "time_limit",
        "service_unavailable",
        "build_failed",
        "population_unsupported",
        "world_start_failed",
        "world_operation_failed",
    ],
    UnrecognizedStr,
]
r"""Bounded failure reason for selecting recovery guidance, or null when unavailable. Older servers can omit this field."""


class WorldErrorTypedDict(TypedDict):
    code: WorldErrorCode
    r"""Stable World error code."""
    detail: str
    r"""Safe human-readable error detail."""
    reason: Nullable[WorldErrorReason]
    r"""Bounded failure reason for selecting recovery guidance, or null when unavailable. Older servers can omit this field."""


class WorldError(BaseModel):
    code: WorldErrorCode
    r"""Stable World error code."""

    detail: str
    r"""Safe human-readable error detail."""

    reason: Nullable[WorldErrorReason]
    r"""Bounded failure reason for selecting recovery guidance, or null when unavailable. Older servers can omit this field."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
