"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .resourceerror import ResourceError, ResourceErrorTypedDict
from .worldsimulation import WorldSimulation, WorldSimulationTypedDict
from continuous.types import BaseModel, Nullable, UNSET_SENTINEL, UnrecognizedStr
from datetime import datetime
from pydantic import model_serializer
from typing import List, Literal, Union
from typing_extensions import TypedDict


WorldStatus = Union[
    Literal[
        "building",
        "ready",
        "running",
        "stopped",
        "failed",
        "canceled",
    ],
    UnrecognizedStr,
]
r"""Current World lifecycle status."""


class WorldTypedDict(TypedDict):
    created_at: datetime
    r"""Time when the World build started."""
    error: Nullable[ResourceErrorTypedDict]
    id: str
    r"""Stable World ID."""
    instructions: str
    r"""Build guidance stored with the World."""
    simulations: List[WorldSimulationTypedDict]
    r"""Created member Simulations. This list is empty before first start."""
    simulators: List[str]
    r"""Stable Simulator IDs in member order."""
    status: WorldStatus
    r"""Current World lifecycle status."""


class World(BaseModel):
    created_at: datetime
    r"""Time when the World build started."""

    error: Nullable[ResourceError]

    id: str
    r"""Stable World ID."""

    instructions: str
    r"""Build guidance stored with the World."""

    simulations: List[WorldSimulation]
    r"""Created member Simulations. This list is empty before first start."""

    simulators: List[str]
    r"""Stable Simulator IDs in member order."""

    status: WorldStatus
    r"""Current World lifecycle status."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
