"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel, UnrecognizedStr
from typing import Literal, Union
from typing_extensions import TypedDict


WorldErrorCode = Union[
    Literal[
        "world_build_canceled",
        "world_start_failed",
        "world_create_failed",
        "world_failed",
        "world_population_failed",
        "world_population_unsupported",
        "world_population_invalid",
        "world_population_unavailable",
    ],
    UnrecognizedStr,
]
r"""Stable World error code."""


class WorldErrorTypedDict(TypedDict):
    code: WorldErrorCode
    r"""Stable World error code."""
    detail: str
    r"""Safe human-readable error detail."""


class WorldError(BaseModel):
    code: WorldErrorCode
    r"""Stable World error code."""

    detail: str
    r"""Safe human-readable error detail."""
