"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .worldrecordcount import WorldRecordCount, WorldRecordCountTypedDict
from continuous.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class WorldDataSummaryTypedDict(TypedDict):
    assumptions: List[str]
    r"""Defaults and inferred choices used to prepare the starting data."""
    records: List[WorldRecordCountTypedDict]
    r"""Observed starting record counts for each member and record type."""
    relationships: List[str]
    r"""Shared relationships checked against the data and served API values."""


class WorldDataSummary(BaseModel):
    assumptions: List[str]
    r"""Defaults and inferred choices used to prepare the starting data."""

    records: List[WorldRecordCount]
    r"""Observed starting record counts for each member and record type."""

    relationships: List[str]
    r"""Shared relationships checked against the data and served API values."""
