"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .buildtoolcall import BuildToolCall, BuildToolCallTypedDict
from .worlddatasummary import WorldDataSummary, WorldDataSummaryTypedDict
from continuous.types import BaseModel, Nullable, UNSET_SENTINEL, UnrecognizedStr
from pydantic import model_serializer
from typing import List, Literal, Union
from typing_extensions import TypedDict


WorldBuildProgressBuilder = Union[
    Literal[
        "openai",
        "claude",
    ],
    UnrecognizedStr,
]
r"""Selected model provider, or null for a build created before provider selection."""


WorldBuildProgressLastSubmission = Union[
    Literal[
        "accepted",
        "rejected",
    ],
    UnrecognizedStr,
]
r"""Outcome of the most recent plan submission, or null."""


LastValidationCode = Union[
    Literal[
        "invalid_plan",
        "unsupported_claim",
        "invalid_requirement",
        "nested_proof",
        "request_not_satisfied",
        "verification_unavailable",
    ],
    UnrecognizedStr,
]
r"""Fixed code for the latest validation finding. Null when no finding is available. Authored details stay private."""


WorldBuildProgressModel = Union[
    Literal[
        "gpt-6-astra",
        "gpt-6-sol",
        "claude-opus-5-5",
        "claude-fable-5-1",
    ],
    UnrecognizedStr,
]
r"""The model the builder and reviewer run on, or null for a build created before provider selection. A build recorded before model selection reports its provider's default."""


WorldBuildProgressPhase = Union[
    Literal[
        "build",
        "review",
        "finalize",
    ],
    UnrecognizedStr,
]
r"""Agent phase: build for generation, review for the separate reviewer, finalize for author repair after review. Null when not recorded."""


ReviewStatus = Union[
    Literal[
        "pending",
        "accepted",
        "rejected",
    ],
    UnrecognizedStr,
]
r"""Status of the original independent review, not approval of later edits. Null before review."""


WorldBuildProgressStage = Union[
    Literal[
        "planning",
        "generating",
        "validating",
        "reviewing",
        "complete",
    ],
    UnrecognizedStr,
]
r"""Internal step of starting-data preparation."""


class WorldBuildProgressTypedDict(TypedDict):
    builder: Nullable[WorldBuildProgressBuilder]
    r"""Selected model provider, or null for a build created before provider selection."""
    last_submission: Nullable[WorldBuildProgressLastSubmission]
    r"""Outcome of the most recent plan submission, or null."""
    last_tool: Nullable[str]
    r"""Name of the most recent tool, or null. Tool arguments and output are private."""
    last_validation_code: Nullable[LastValidationCode]
    r"""Fixed code for the latest validation finding. Null when no finding is available. Authored details stay private."""
    model: Nullable[WorldBuildProgressModel]
    r"""The model the builder and reviewer run on, or null for a build created before provider selection. A build recorded before model selection reports its provider's default."""
    phase: Nullable[WorldBuildProgressPhase]
    r"""Agent phase: build for generation, review for the separate reviewer, finalize for author repair after review. Null when not recorded."""
    recent_tools: List[BuildToolCallTypedDict]
    r"""The most recent tool calls, oldest first, at most 20."""
    review_status: Nullable[ReviewStatus]
    r"""Status of the original independent review, not approval of later edits. Null before review."""
    stage: WorldBuildProgressStage
    r"""Internal step of starting-data preparation."""
    submissions: int
    r"""Number of distinct candidate plans submitted."""
    summary: Nullable[WorldDataSummaryTypedDict]
    r"""Verified starting data, or null before a completed build."""
    tests: int
    r"""Number of distinct candidate plans tested. Zero when not recorded."""
    tool_calls: int
    r"""Number of agent tool calls."""


class WorldBuildProgress(BaseModel):
    builder: Nullable[WorldBuildProgressBuilder]
    r"""Selected model provider, or null for a build created before provider selection."""

    last_submission: Nullable[WorldBuildProgressLastSubmission]
    r"""Outcome of the most recent plan submission, or null."""

    last_tool: Nullable[str]
    r"""Name of the most recent tool, or null. Tool arguments and output are private."""

    last_validation_code: Nullable[LastValidationCode]
    r"""Fixed code for the latest validation finding. Null when no finding is available. Authored details stay private."""

    model: Nullable[WorldBuildProgressModel]
    r"""The model the builder and reviewer run on, or null for a build created before provider selection. A build recorded before model selection reports its provider's default."""

    phase: Nullable[WorldBuildProgressPhase]
    r"""Agent phase: build for generation, review for the separate reviewer, finalize for author repair after review. Null when not recorded."""

    recent_tools: List[BuildToolCall]
    r"""The most recent tool calls, oldest first, at most 20."""

    review_status: Nullable[ReviewStatus]
    r"""Status of the original independent review, not approval of later edits. Null before review."""

    stage: WorldBuildProgressStage
    r"""Internal step of starting-data preparation."""

    submissions: int
    r"""Number of distinct candidate plans submitted."""

    summary: Nullable[WorldDataSummary]
    r"""Verified starting data, or null before a completed build."""

    tests: int
    r"""Number of distinct candidate plans tested. Zero when not recorded."""

    tool_calls: int
    r"""Number of agent tool calls."""

    @model_serializer(mode="wrap")
    def _serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
