"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel
from typing_extensions import TypedDict


class WorldRecordCountTypedDict(TypedDict):
    count: int
    r"""Number of stored starting records of this type."""
    entity: str
    r"""Record type reported by the Simulator."""
    member_index: int
    r"""Position in the selected Simulator list, starting at zero."""
    simulator_id: str
    r"""Stable ID of the Simulator for this member."""


class WorldRecordCount(BaseModel):
    count: int
    r"""Number of stored starting records of this type."""

    entity: str
    r"""Record type reported by the Simulator."""

    member_index: int
    r"""Position in the selected Simulator list, starting at zero."""

    simulator_id: str
    r"""Stable ID of the Simulator for this member."""
