"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .worldbuildprogress import WorldBuildProgress, WorldBuildProgressTypedDict
from .worlderror import WorldError, WorldErrorTypedDict
from .worldsimulation import WorldSimulation, WorldSimulationTypedDict
from continuous.types import BaseModel, Nullable, UNSET_SENTINEL, UnrecognizedStr
from datetime import datetime
from pydantic import model_serializer
from typing import Any, List, Literal, Union
from typing_extensions import TypedDict


WorldStatus = Union[
    Literal[
        "pending",
        "building",
        "ready",
        "running",
        "stopped",
        "failed",
        "canceled",
    ],
    UnrecognizedStr,
]
r"""pending while waiting for capacity; building while the build runs; ready when it can be started; running or stopped once its Simulations exist; failed when building or first start fails; canceled when the build was canceled."""


class WorldTypedDict(TypedDict):
    active_advance_id: Nullable[str]
    r"""Current clock advance operation ID, or null."""
    build: Nullable[WorldBuildProgressTypedDict]
    r"""The build's latest progress report and verified starting data, or null before the first report."""
    created_at: datetime
    r"""Time when the World was created."""
    current_time: datetime
    r"""Current shared simulated time."""
    error: Nullable[WorldErrorTypedDict]
    id: str
    r"""World ID."""
    instructions: str
    r"""Instructions for the initial synthetic data and relationships."""
    metadata: Any
    r"""Customer JSON metadata, or null."""
    name: str
    r"""Name for the World."""
    simulations: List[WorldSimulationTypedDict]
    r"""Created member Simulations. This list is empty before first start."""
    simulators: List[str]
    r"""Simulator IDs in member order."""
    start_time: datetime
    r"""Simulated time the World starts at: chosen at build, and changeable on the first Start."""
    status: WorldStatus
    r"""pending while waiting for capacity; building while the build runs; ready when it can be started; running or stopped once its Simulations exist; failed when building or first start fails; canceled when the build was canceled."""


class World(BaseModel):
    active_advance_id: Nullable[str]
    r"""Current clock advance operation ID, or null."""

    build: Nullable[WorldBuildProgress]
    r"""The build's latest progress report and verified starting data, or null before the first report."""

    created_at: datetime
    r"""Time when the World was created."""

    current_time: datetime
    r"""Current shared simulated time."""

    error: Nullable[WorldError]

    id: str
    r"""World ID."""

    instructions: str
    r"""Instructions for the initial synthetic data and relationships."""

    metadata: Any
    r"""Customer JSON metadata, or null."""

    name: str
    r"""Name for the World."""

    simulations: List[WorldSimulation]
    r"""Created member Simulations. This list is empty before first start."""

    simulators: List[str]
    r"""Simulator IDs in member order."""

    start_time: datetime
    r"""Simulated time the World starts at: chosen at build, and changeable on the first Start."""

    status: WorldStatus
    r"""pending while waiting for capacity; building while the build runs; ready when it can be started; running or stopped once its Simulations exist; failed when building or first start fails; canceled when the build was canceled."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
