"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .worlddatasummary import WorldDataSummary, WorldDataSummaryTypedDict
from continuous.types import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from pydantic import model_serializer
from typing import Literal, Optional, Union
from typing_extensions import NotRequired, TypedDict


Stage = Union[
    Literal[
        "planning",
        "generating",
        "validating",
        "complete",
    ],
    UnrecognizedStr,
]
r"""Current phase of starting-data preparation."""


class WorldBuildTypedDict(TypedDict):
    stage: Stage
    r"""Current phase of starting-data preparation."""
    summary: NotRequired[WorldDataSummaryTypedDict]


class WorldBuild(BaseModel):
    stage: Stage
    r"""Current phase of starting-data preparation."""

    summary: Optional[WorldDataSummary] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["summary"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
