"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.types import BaseModel
from typing_extensions import TypedDict


class WorldSimulationTypedDict(TypedDict):
    id: str
    r"""ID of the created Simulation."""
    simulator_id: str
    r"""ID of the Simulator that this Simulation runs."""


class WorldSimulation(BaseModel):
    id: str
    r"""ID of the created Simulation."""

    simulator_id: str
    r"""ID of the Simulator that this Simulation runs."""
