"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .worlddatasummary import WorldDataSummary, WorldDataSummaryTypedDict
from continuous.types import BaseModel, Nullable, UNSET_SENTINEL, UnrecognizedStr
from pydantic import model_serializer
from typing import Literal, Union
from typing_extensions import TypedDict


WorldBuildProgressLastSubmission = Union[
    Literal[
        "accepted",
        "rejected",
    ],
    UnrecognizedStr,
]
r"""Outcome of the most recent plan submission, or null."""


WorldBuildProgressModel = Union[
    Literal[
        "gpt-6-astra",
        "gpt-6.1-sol",
        "claude-opus-5-5",
        "claude-fable-5-1",
        "gpt-6-sol",
    ],
    UnrecognizedStr,
]
r"""The model the builder and reviewer run on, or null for a build created before provider selection. A build recorded before model selection reports its provider's default."""


WorldBuildProgressPhase = Union[
    Literal[
        "build",
        "review",
        "finalize",
    ],
    UnrecognizedStr,
]
r"""Agent phase: build for generation, review for the separate reviewer, finalize for author repair after review. Null when not recorded."""


WorldBuildProgressStage = Union[
    Literal[
        "planning",
        "generating",
        "validating",
        "reviewing",
        "complete",
    ],
    UnrecognizedStr,
]
r"""planning while the build prepares; generating while the builder writes starting data; validating while the data is checked through the Simulators' APIs; reviewing while the separate reviewer checks it; complete when verified starting data is saved."""


class WorldBuildProgressTypedDict(TypedDict):
    last_submission: Nullable[WorldBuildProgressLastSubmission]
    r"""Outcome of the most recent plan submission, or null."""
    last_tool: Nullable[str]
    r"""Name of the most recent tool call, or null. Tool arguments and output are private."""
    model: Nullable[WorldBuildProgressModel]
    r"""The model the builder and reviewer run on, or null for a build created before provider selection. A build recorded before model selection reports its provider's default."""
    phase: Nullable[WorldBuildProgressPhase]
    r"""Agent phase: build for generation, review for the separate reviewer, finalize for author repair after review. Null when not recorded."""
    stage: WorldBuildProgressStage
    r"""planning while the build prepares; generating while the builder writes starting data; validating while the data is checked through the Simulators' APIs; reviewing while the separate reviewer checks it; complete when verified starting data is saved."""
    submissions: int
    r"""Number of distinct candidate plans submitted."""
    summary: Nullable[WorldDataSummaryTypedDict]
    r"""Verified starting data, or null before a completed build."""
    tool_calls: int
    r"""Number of agent tool calls."""


class WorldBuildProgress(BaseModel):
    last_submission: Nullable[WorldBuildProgressLastSubmission]
    r"""Outcome of the most recent plan submission, or null."""

    last_tool: Nullable[str]
    r"""Name of the most recent tool call, or null. Tool arguments and output are private."""

    model: Nullable[WorldBuildProgressModel]
    r"""The model the builder and reviewer run on, or null for a build created before provider selection. A build recorded before model selection reports its provider's default."""

    phase: Nullable[WorldBuildProgressPhase]
    r"""Agent phase: build for generation, review for the separate reviewer, finalize for author repair after review. Null when not recorded."""

    stage: WorldBuildProgressStage
    r"""planning while the build prepares; generating while the builder writes starting data; validating while the data is checked through the Simulators' APIs; reviewing while the separate reviewer checks it; complete when verified starting data is saved."""

    submissions: int
    r"""Number of distinct candidate plans submitted."""

    summary: Nullable[WorldDataSummary]
    r"""Verified starting data, or null before a completed build."""

    tool_calls: int
    r"""Number of agent tool calls."""

    @model_serializer(mode="wrap")
    def _serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
