"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .continuouserror import ContinuousError
from typing import Any, TYPE_CHECKING

from continuous.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .continuousdefaulterror import ContinuousDefaultError
    from .error import Error, ErrorData
    from .no_response_error import NoResponseError
    from .responsevalidationerror import ResponseValidationError

__all__ = [
    "ContinuousDefaultError",
    "ContinuousError",
    "Error",
    "ErrorData",
    "NoResponseError",
    "ResponseValidationError",
]

_dynamic_imports: dict[str, str] = {
    "ContinuousDefaultError": ".continuousdefaulterror",
    "Error": ".error",
    "ErrorData": ".error",
    "NoResponseError": ".no_response_error",
    "ResponseValidationError": ".responsevalidationerror",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
