"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from continuous.errors import ContinuousError
from continuous.types import BaseModel
from dataclasses import dataclass, field
import httpx
from typing import Optional


class ErrorData(BaseModel):
    code: str
    r"""Stable machine-readable error code."""
    detail: str
    r"""Safe human-readable error detail."""


@dataclass(unsafe_hash=True)
class Error(ContinuousError):
    data: ErrorData = field(hash=False)

    def __init__(
        self, data: ErrorData, raw_response: httpx.Response, body: Optional[str] = None
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
